### ISSUE TITLE
some of the updateStream files are empty

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_snb_datagen_spark#1]
Hi,
Seems that when generating SF1 on 24 threads, some of the update stream files are generated empty, causing a Null pointer error in the ldbc driver. FYI @ArnauPrat and @alexaverbuch 
Tomer

**Comment by ArnauPrat** [comment]
Hi Tomer,

I assume that you have updateStream:true set to true. Can you send me by 
email the console output of the generator?

Arnau

**Comment by tomersagi** [comment]
Hi,
Yes, and here it is.
Tomer

**Comment by tomersagi** [comment]
After the latest revision, I still get a lot of empties.

**Comment by ArnauPrat** [comment]
This should be fixed, in the sense that those files generated by reducers not receiving any compute block, are now automatically deleted before finishing the execution.

Arnau

**Comment by tomersagi** [comment]
hmm, nope:
    
    -rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_10_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_10_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_1_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_1_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_11_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_11_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_12_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_12_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_13_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_13_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_14_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_14_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_15_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_15_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_16_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_16_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_17_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_17_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_18_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_18_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_19_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_19_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_20_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_20_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_2_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_2_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_21_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_21_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_22_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_22_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_23_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_23_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_3_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_3_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_4_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_4_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_5_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_5_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_6_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_6_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_7_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_7_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_8_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_8_0_person.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_9_0_forum.csv
-rw-r--r-- 1 sagit sagit       0 Jan 29 06:12 updateStream_9_0_person.csv

**Comment by ArnauPrat** [comment]
Are you running with 24 threads and SF1 right?

**Comment by tomersagi** [comment]
yes
