### ISSUE TITLE
Syntax error in generateparams.py

### ISSUE THREAD

**Issue by andralungu** [ldbc/ldbc_snb_datagen_spark#10]
Hi,

I am new to LDBC. I'd like to play with it to generate a nice 50 billion vertex graph :). 
For now, all I did was to snoop around the guidelines and to place the contents of ldbc_snb_datagen on my cluster nodes. I saw that you guys have a script that runs everything so I tried sh run.sh; beforehand I modified the first two lines to contain the correct paths...

Still I get this error:

---
- Serializing invariant schema  *
  ************************************************
  146 total seconds
  Person generation time: 5
  University correlated edge generation time: 4
  Interest correlated edge generation time: 6
  Random correlated edge generation time: 7
  Person serialization time: 8
  Person activity generation and serialization time: 67
  Sorting update streams time: 48
  Invariant schema serialization time: 0
  Total Execution time: 146
  File "paramgenerator/generateparams.py", line 92
    def handlePairCountryParam((Country1, Country2)):
                               ^
  SyntaxError: invalid syntax

I am sure I am doing it wrong, but could someone please explain what? Needless to say I did not touch that python script. 

Thanks!
Andra

**Comment by ArVr** [comment]
Hi Andra!

Could you check in your terminal if Java_home is set right? <code> echo $JAVA_HOME </code>. If u see nothing you have to set your JAVA_home parameter.

Greats!

Aron

**Comment by andralungu** [comment]
Hi Aron!

It appears to be set:
andra.lungu@wally011 ~ $ echo $JAVA_HOME
/etc/java-config-2/current-system-vm

**Comment by andralungu** [comment]
The problem is that you're using python 2.7. The latest version no longer supports "((" -tuple arguments-. I ran this with python 2.
