### ISSUE TITLE
The generated CSV header for interactive query 2, 9 doesn't match the specification

### ISSUE THREAD

**Issue by benhamad** [ldbc/ldbc_snb_datagen_spark#106]
In the LDCB specification, for the interactive queries 2 and 9 they need a `maxDate` parameter. Where the CSV header for the generated params files have `minDate` instead.

```
$ head -n 1 interactive_2_param.txt
personId|minDate
$ head -n 1 interactive_9_param.txt
personId|minDate
```

**Comment by szarnyasg** [comment]
Good catch, thanks! The error is in the bottom part of this code snippet:

https://github.com/ldbc/ldbc_snb_datagen/blob/f466302f36f6527ac05bbe59b96c7c8ff2e3a838/paramgenerator/generateparams.py#L196-L240

I could not fix this in a couple of minutes of trying and will defer this to the Julia rewrite (#83) task.

**Comment by szarnyasg** [comment]
Update: it seems I managed to resolve this with ad900890f0926601a191e52443aae42e8a14bb06.
