### ISSUE TITLE
Missing distribution.R in the tools folder

### ISSUE THREAD

**Issue by andralungu** [ldbc/ldbc_snb_datagen_spark#11]
So now that I have my nice generated graph, I wanted to use the degreeAnaysis script provided in the tools folder. The problem is that it calls this distribution R script that seems to have been lost (there's just a cumulative.R). For me it's fine, I have my own R script that does that, I just need to do some `awk`s to bring it to the desired form. I just thought it would be nice to let you guys know about this one. Maybe I'm doing something wrong?  

Thanks!
Andra

**Comment by ArnauPrat** [comment]
Sorry for that Andra, I just pushed the script. The thing is that I just made this tools for internal use I did not expecte anybody else to use them, so they are not very polished :P

**Comment by andralungu** [comment]
Thanks! Don't worry about it :)
It's always good to make scripts ready for public use, you never know!
