### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by ubaid4j** [ldbc/ldbc_snb_datagen_spark#113]
**OS**: Ubuntu 18.04.3 LTS
**Java**: openjdk 11.0.6 2020-01-14

### How to Produce
1. cp params-csv-basic.ini params.ini
2. wget http://archive.apache.org/dist/hadoop/core/hadoop-3.2.1/hadoop-3.2.1.tar.gz
3. tar xf hadoop-3.2.1.tar.gz
4. export HADOOP_CLIENT_OPTS="-Xmx2G"
5. export HADOOP_HOME=`pwd`/hadoop-3.2.1
6. export LDBC_SNB_DATAGEN_HOME=`pwd`
7. ./run.sh

### Stack Trace

        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-pmd-plugin/maven-metadata.xml
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-pmd-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-pmd-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-pmd-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-pmd-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-maven-plugin/maven-metadata.xml
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-maven-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-maven-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-maven-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-maven-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-javalang-plugin/maven-metadata.xml
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-javalang-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-javalang-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-javalang-plugin/
        SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/walkmod/walkmod-javalang-plugin/

### Note:
[After resolving this issue](https://github.com/ldbc/ldbc_snb_driver/issues/116)

**Comment by szarnyasg** [comment]
The walkmod issue was fixed by 6eaf506a80d95ddf93d2523a989dbc1b6c882f9d.
Leaving this open for the Maven issue.

**Comment by ubaid4j** [comment]
Thanks, its working...
