### ISSUE TITLE
Add support for Parquet serializers

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#121]
[Parquet](https://parquet.apache.org/documentation/latest/) is a "compressed, efficient columnar data representation available to any project in the Hadoop ecosystem". We could put it to good use to reduce the space required by the outputs. It'd need be implement the same decompositions as the CSV files do, i.e. `basic`, `composite`, `merge-foreign`, and `composite-merge-foreign`.

**Comment by dszakallas** [comment]
Not just a space, scanning Parquet has several optimizations. You can push down filters so the reader doesn't deserialize rows that would be eliminated by a later filter step (even discarding whole files by filename without opening a file stream, if it was partitioned by the filter predicate). Column projections can be pushed down too avoiding unnecessary column reads. Counting number of rows is in effect reading a metadata footer value.
