### ISSUE TITLE
Missing substitution parameters for BI when SF >= 30

### ISSUE THREAD

**Issue by coolerzxw** [ldbc/ldbc_snb_datagen_spark#124]
Hi, we want to run the BI workload at larger scales but found that the generated subsitution parameters are missing for some queries when SF is >= 30 (e.g. BI 4 and 9 for SF 100).

**Comment by szarnyasg** [comment]
@coolerzxw regrettably, your observation is correct. I don't know a quick fix for this as we're currently revamping the benchmarking (getting rid of a few queries, introducing new ones and rewriting paramgen). In the meantime, feel free to use create your own substitution parameters by hacking the existing Python2 script.

**Comment by szarnyasg** [comment]
We are still working on the BI parameter generator. To be continued in #236
