### ISSUE TITLE
Missing setting name in Configuration documentation

### ISSUE THREAD

**Issue by thSoft** [ldbc/ldbc_snb_datagen_spark#127]
In https://github.com/ldbc/ldbc_snb_datagen/wiki/Configuration#configuring-the-runsh-script, there is a line:

> ``: whether the parameters for SNB queries are generated

The setting's name is missing (``).

**Comment by szarnyasg** [comment]
@thSoft thanks, I fixed the documentation and added that this is a deprecated feature. If you don't want to generate the parameters, your best option is to delete the `paramgenerator` directory. (The generator will print some error messages but the overall process will not fail.)
