### ISSUE TITLE
Temporal distribution of Posts and Comments

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#128]
Related code bits --

Posts are random - that's good:
https://github.com/ldbc/ldbc_snb_datagen/blob/9c0f6b04106ab9cd5da4f9eb39e0397116512936/src/main/java/ldbc/snb/datagen/generator/generators/postgenerators/PostGenerator.java#L139-L140

Comments use a random power-law function:
https://github.com/ldbc/ldbc_snb_datagen/blob/9c0f6b04106ab9cd5da4f9eb39e0397116512936/src/main/java/ldbc/snb/datagen/generator/generators/CommentGenerator.java#L131-L136

https://github.com/ldbc/ldbc_snb_datagen/blob/9c0f6b04106ab9cd5da4f9eb39e0397116512936/src/main/java/ldbc/snb/datagen/util/DateUtils.java#L197-L199

**Comment by jackwaudby** [comment]
Done some digging into the power-law distribution used by Comments. Comments always occur within 1 day of their parent message following the power-law distribution below

![comments_powerlaw](https://user-images.githubusercontent.com/33488812/77080556-53ab6e00-69f1-11ea-9f10-affc50fb0520.png)

The distributions shape parameter is set in `DatagenParams` to 0.4. The mean between is 6.85 hours. 

FYI, the comment lifespan was half-implemented, this has now been fully implemented in 8e5a70ba473d00d81fc5dfb5a451a7f38ccb6708 

Posts seems random, will investigate to confirm

**Comment by jackwaudby** [comment]
Can confirm Posts generation is uniformly distributed on the lifespan interval.
