### ISSUE TITLE
How to load parameters

### ISSUE THREAD

**Issue by FranciscoMonteiro694** [ldbc/ldbc_snb_datagen_spark#132]
Hey fellas!
First of all, i'm not sure if this is the right place to ask.
Me and my colleague are doing a project for university using this benchmark and we are struggling with a simple step.
We have the whole scenario set up and we also generated the parameters and we would like to know how can we load this parameters, in .txt format into our queries, without inserting them by hand. I'm not sure if i'm making myself clear.
I was hoping someone could help us.
Thank you for you help!

**Comment by szarnyasg** [comment]
Hi @FranciscoMonteiro694,
> First of all, i'm not sure if this is the right place to ask.
Sure, feel free to ask in LDBC repositories.

For handling parameters, you'll need the [driver](https://github.com/ldbc/ldbc_snb_driver) and the [implementations](https://github.com/ldbc/ldbc_snb_implementations) repository.

Can you provide some details on the nature of your experiments? (Targeted system, workload, etc.)

Also, it's worth keeping in mind that LDBC SNB currently has two major variants: the stable version ([specification](https://arxiv.org/abs/2001.02299)) is on the `master` branch of the repositories, while the development of the next version (featuring full-fledged delete operations) is ongoing on the `dev` branches.

**Comment by FranciscoMonteiro694** [comment]
> Hi @FranciscoMonteiro694,
> 
> > First of all, i'm not sure if this is the right place to ask.
> > Sure, feel free to ask in LDBC repositories.
> 
> For handling parameters, you'll need the [driver](https://github.com/ldbc/ldbc_snb_driver) and the [implementations](https://github.com/ldbc/ldbc_snb_implementations) repository.
> 
> Can you provide some details on the nature of your experiments? (Targeted system, workload, etc.)
> 
> Also, it's worth keeping in mind that LDBC SNB currently has two major variants: the stable version ([specification](https://arxiv.org/abs/2001.02299)) is on the `master` branch of the repositories, while the development of the next version (featuring full-fledged delete operations) is ongoing on the `dev` branches.

First of all, thank you so much for your reply.
We are doing a simple experiment for a Data management class, and we are using Neo4j. Our goal in this milestone is to run the queries using the parameters generated. 
We generated the parameters using generateparams.py, then we used build.sh and after that we tried running the interactive-create-validation-parameters.sh
We've tried to change the properties in order to only create a small amount of parameters, but it keeps creating a number (46) that we cannot understand where it comes from.
For this milestone we only want to create a few number of parameters, 10 or so, to run a few queries.
Thank you for you help!

**Comment by szarnyasg** [comment]
> We've tried to change the properties in order to only create a small amount of parameters, but it keeps creating a number (46) that we cannot understand where it comes from.

Paramgen always generates the same number of parameter, this is something that currently cannot be tuned.
Paramgen currently is also rather slow - this is something we're looking in the near future. For the time being, I have the parameters pre-generated. E.g. SF1 is here: https://www.dropbox.com/s/iipb1412kh3szen/sf1.zip?dl=0
Which scale factors are you targeting?

**Comment by PedroMarquesSa** [comment]
Hi, I'm working with @FranciscoMonteiro694 in this project
Thanks for the quick answer, we are striving to use an SF of 10 down the line but for now, we are using SF = 1
Our main doubt is the properties defined in the interactive-create-validation-parameters.properties... Some of them, we are not fully understanding... The operationcount is the max number of repetitions of all queries right?
Is it distributed by all queries randomly or does it have some sort of criteria?
For example, with an operationcount = 250 the maximum count of a query was 24, so it used 24 different substitution parameters, right? (I can be totally and utterly mistaken here, we are quite new to all this)

**Comment by jackwaudby** [comment]
Hey @PedroMarquesSa @FranciscoMonteiro694 

_The operationcount is the max number of repetitions of all queries right?_ 
Thats what you'd expect but unfortunately its a little counter intuitive...

Complex reads are expressed in numbers of update operations that must execute per instance. E.g. For complex read 1, 26 updates must occur between each complex read 1. Short reads happen in sequences of random length and are determined at runtime - using the results of complex reads as inputs.  Only the complex reads take their parameters from `substitution_parameters`.

With this is mind the number of operations generated when running `interactive-create-validation-parameters` is determined as follows: first, floor(`operation_count`/(number of complex reads enabled + number of updates enabled)) is calculated which determines the number for each complex read query. E.g `operation_count=100` translates to 4 of each complex reads. Then a number of update operations must be executed needed to get 4 of each complex read, these are filtered so you don't end you with 2000+ updates (to get 4 complex read 9s for example).  The short reads are generated after each complex read. This is why it easily blows past the specified `operation_count`. 

Hope this helps - we are working on making this clearer in the documentation and looking at improving the method by which validation parameters are generated. 

Best, 

Jack

**Comment by PedroMarquesSa** [comment]
Hi @jackwaudby 

Thanks for the extended answer, we have been working on other assignments and it's only now that we managed to come back to this project. 
We understand that the way that the driver works is to optimize the number of operations needed, so it has its order right? We are still getting into it, to better understand the workflow and we were wondering for example, given ```operation_count=100``` if there's an optimal way to know how many validation parameters to generate.
In the example, you gave we can see that 100 ```operation count``` translates into 4 of each complex reads given that ```4=floor(100/(14+8))``` but it isn't clear to us what value to give in the ```create_validation_parameters``` in order to have the sufficient amount to run the benchmark itself. 
We are having some difficulties understanding the validation parameters part is what I'm saying.

Again, thank you so much for the help,

Pedro Sá

**Comment by jackwaudby** [comment]
Hi @PedroMarquesSa 

At a high-level a benchmark workflow goes like this, I'm assuming you want to implement the SNB interactive workload:
1. [implement your database connector](https://github.com/ldbc/ldbc_snb_driver/wiki/Implementing-a-Database-Connector) 
2. generate the benchmark data using the data generator. (`social_network`, `substitution_parameters`, `updateStreams`)
3. validate your database connector and queries
      a) use a [reference implementation](https://github.com/ldbc/ldbc_snb_implementations) to generate a `validation_params`. 
      b) load social_network into your database and use the driver to validate your database connector and queries against `validation_params`. 
4. if you pass validation you can then execute the benchmark. note, the validation parameters you create are not used in this step. 

The actual `operation count` value you supply in 3a) is not _too_ important. When you create the validation parameters you will at least have 1 instance of each query. 

Hopefully this provides some clarity on the whole process

Jack

**Comment by PedroMarquesSa** [comment]
Hey @jackwaudby 

We've configurated the driver in order to run with ```operation_count=750``` but we realized that not all queries were performed... is there a known minimum value for ```operation_count```in order to run all complex queries?

Thanks once again for the explanation

Pedro Sá

**Comment by jackwaudby** [comment]
Which specific queries are not being performed? 

One possibility is that not all queries are enabled in the `.properties` file you supply to the driver. 

Can you verify` ldbc.snb.interactive.<op>_enable=true` for all operation types? 

Jack

**Comment by jackwaudby** [comment]
Also;

- Which reference implementation did you use to generate the `validation_params.csv`?
- Are you using the `master` branches for both the driver and reference implementations?

**Comment by PedroMarquesSa** [comment]
We checked that before and all queries are set to ```true```
It was running with ```operation count = 750```and it didn't perform 3,5,6 and 9

We have the cypher and yes, we are using the master but it's not up to date, it's from nearly a month ago when we started.
We didn't generate the validation_params this time, we were just experimenting to see whether all queries ran with operation count set to 750.

**Comment by jackwaudby** [comment]
My confusion with your issue is arising from whether you are trying to run the validation phase as you mentioned `interactive-create-validation-parameters.properties` in an earlier comment or run the benchmark phase? 

I've been through the benchmark workflow using the `cypher` implementation. If you let me know where we differ I should be able to help out more :) 

1. Generated SF1 using datagen. 
2. Loaded the data in Neo4j and ran `interactive-create-validation-parameters.sh` with`create_validation_parameters=validation_params.csv|100`
This generated 1451 parameters and results. 
3. Ran `interactive-validate.sh` with `validate_database=validation_params.csv`
```
  Successfully executed 29 operation types
    4 / 4              LdbcQuery1
    4 / 4              LdbcQuery10
    4 / 4              LdbcQuery11
    4 / 4              LdbcQuery12
    4 / 4              LdbcQuery13
    4 / 4              LdbcQuery14
    4 / 4              LdbcQuery2
    4 / 4              LdbcQuery3
    4 / 4              LdbcQuery4
    4 / 4              LdbcQuery5
    1 / 1              LdbcQuery6
    4 / 4              LdbcQuery7
    4 / 4              LdbcQuery8
    1 / 1              LdbcQuery9
    248 / 248            LdbcShortQuery1PersonProfile
    234 / 234            LdbcShortQuery2PersonPosts
    244 / 244            LdbcShortQuery3PersonFriends
    136 / 136            LdbcShortQuery4MessageContent
    136 / 136            LdbcShortQuery5MessageCreator
    136 / 136            LdbcShortQuery6MessageForum
    23 / 23             LdbcShortQuery7MessageReplies
    4 / 4              LdbcUpdate1AddPerson
    28 / 28             LdbcUpdate2AddPostLike
    29 / 29             LdbcUpdate3AddCommentLike
    4 / 4              LdbcUpdate4AddForum
    96 / 96             LdbcUpdate5AddForumMembership
    38 / 38             LdbcUpdate6AddPost
    41 / 41             LdbcUpdate7AddComment
    4 / 4              LdbcUpdate8AddFriendship
```
Each query is represented at least once. 
4. Ran `interactive-benchmark.sh` with `operation_count=2000`. 
In this execution each complex read executed at least once

**Comment by FranciscoMonteiro694** [comment]
Hello guys.
Just wanted you to know that we finished our assignment. Hopefully we can get a good grade!
Thank you very much for the time you invested helping us :)
Best regards,
Francisco and Pedro!

**Comment by szarnyasg** [comment]
Fantastic! Glad we could help.

Stay safe,
The SNB task force

**Comment by winattack** [comment]
in create validation parameters step, can not generate validation parameters for short query, does any one know why? below is my .properties file:
ldbc.snb.interactive.LdbcShortQuery1PersonProfile_enable=true
ldbc.snb.interactive.LdbcShortQuery2PersonPosts_enable=true
ldbc.snb.interactive.LdbcShortQuery3PersonFriends_enable=true
ldbc.snb.interactive.LdbcShortQuery4MessageContent_enable=true
ldbc.snb.interactive.LdbcShortQuery5MessageCreator_enable=true
ldbc.snb.interactive.LdbcShortQuery6MessageForum_enable=true
ldbc.snb.interactive.LdbcShortQuery7MessageReplies_enable=true

**Comment by szarnyasg** [comment]
Hello @winattack, you have to enable updates and complex reads to generate validation parameters for short reads. This is a known limitation of the Interactive driver: https://github.com/ldbc/ldbc_snb_interactive_v1_impls/issues/207#issuecomment-981601119
