### ISSUE TITLE
Fix incorrect album filter

### ISSUE THREAD

**Issue by dszakallas** [ldbc/ldbc_snb_datagen_spark#138]
https://github.com/ldbc/ldbc_snb_datagen/blob/4dfb2794c29b4f47bd344fcda1f6c3b8de69bbdb/src/main/java/ldbc/snb/datagen/generator/generators/PersonActivityGenerator.java#L212

should be `album == null`

**Comment by jackwaudby** [comment]
Fixed in 0866246dbb7c1d77848df00fe3c13d4fd12e2438

Note: this is a bit of a hack for when there is not a valid interval to generate an album in.  Definitely a better way to handle such a scenario.
