### ISSUE TITLE
Adding another test scale factor

### ISSUE THREAD

**Issue by jackwaudby** [ldbc/ldbc_snb_datagen_spark#145]
Add a smaller scale factor for testing. 

`SF0.1` has 1700 persons. A size of 50 persons was discussed - how about we call it `SF0.05`

What do you think @szarnyasg ?

**Comment by szarnyasg** [comment]
In the composite variant, [this data set](https://github.com/ldbc/ldbc_snb_implementations/tree/dev/cypher/test-data/raw) is 2984 kbytes. So in theory, we could call it `SF0.003` (SF triple-oh-three?). What do you think?

**Comment by jackwaudby** [comment]
Works for me. I believe it just needs adding to `scale_factors.xml`. I will open a PR
