### ISSUE TITLE
Issue timeout hadoop datagen

### ISSUE THREAD

**Issue by francast95** [ldbc/ldbc_snb_datagen_spark#148]
Hi I have issue with timeout in datagen, this is the error:

![image](https://user-images.githubusercontent.com/44240684/80270577-500da580-8687-11ea-9f91-5d79eb08a982.png)

I have reading in troubleshooting and I saw this:

![image](https://user-images.githubusercontent.com/44240684/80270637-dcb86380-8687-11ea-872f-408ae6794449.png)

But I don't know in which hadoop file should I put that code

@szarnyasg

**Comment by szarnyasg** [comment]
@francast95 it belongs to the `mapred-site.xml` file. I updated the wiki with this information. See also the https://github.com/ldbc/ldbc_snb_datagen/wiki/Configuration site.

**Comment by francast95** [comment]
@szarnyasg Ok. What does the following address refer to?

![image](https://user-images.githubusercontent.com/44240684/80283951-59c7f500-86e9-11ea-87dc-d9385bc3bcd2.png)

**Comment by szarnyasg** [comment]
You only need to set this up if you require YARN for your Hadoop setup. It's likely that you don't need it, so I'd recommend following the instructions here: https://hadoop.apache.org/docs/r3.2.1/hadoop-project-dist/hadoop-common/SingleCluster.html

**Comment by francast95** [comment]
Last night I left running the datagen to create 100 gb of data and it reaches to generate only the dynamic folder in snb_implementions and it throws me what appears in the following images

![image](https://user-images.githubusercontent.com/44240684/80284058-07d39f00-86ea-11ea-8715-3f0f5c00a0f5.png)
![image](https://user-images.githubusercontent.com/44240684/80284069-14f08e00-86ea-11ea-8040-c5370c7019fb.png)

In addition I also tried to do it with 10 gb of data and it generated the timeout error but at least it generated all the folders of snb_implementions

**Comment by szarnyasg** [comment]
@francast95 your Hadoop temp directory probably ran out of space, see https://github.com/ldbc/ldbc_snb_datagen/wiki/Troubleshooting#javaioioexception-no-space-left-on-device

Btw, is your thesis work actually generating the data sets or you plan to use them for subsequent tasks? We are aware that Datagen is not easy to set up & run, so I can simply send you links to the data sets in an email if needed.

**Comment by francast95** [comment]
I only need to have sample data to apply my optimization strategies that have already been tested in a 1 GB workload, it is only to check and take statistics that support that my optimization strategies work, in that case of course if you can send me two 10 and 100 gb workloads of the datagen version 0.3.2 by google drive would be perfect and i would really appreciate it

**Comment by szarnyasg** [comment]
Sure, drop me a line at `szarnyas@db.bme.hu`
