### ISSUE TITLE
Wrong q2_params.txt in Bi branch

### ISSUE THREAD

**Issue by ArnauPrat** [ldbc/ldbc_snb_datagen_spark#15]
@mkaufmann 
According to BI query2 specification (http://wiki.ldbcouncil.org/display/TUC/Business+Intelligence+Workload), the query requires five parameters: 
    \* date1 - Date
    \* date2 - Date
    \* country1 - String
    \* country2 - String
    \* endDate - Date

Currently, q2_params.txt file contains something in the form of:

```
Param0|Param1|Param2
494|570|United_States,United_Kingdom,Germany
164|300|Croatia,Egypt,United_Kingdom,Germany
```

It seems that the first two columns do not contain valid dates. Second, the file should contain five columns instead of three. Third, this query does not require three countries but just two, put in separate columns with the correct separator. Something similar to this should be output:

```
Param0|Param1|Param2|Param3|Param4
1330819200000|1339459200000|United_States|Germany|1356998400000
1330819200000|1339459200000|Croatia|Egypt|1356998400000
```

Note that Param4 is the end of simulated time. By now, you can just handcode the epoch value of 2013-01-01 (as I did in this example). This is what I used to make the conversion: http://www.epochconverter.com/

Arnau

**Comment by mkaufmann** [comment]
For param generation the parameters of some queries have to be changed. Two countries did not give enough options to generate consistent parameters. So instead there now is a comma seperated list of countries of varying length. Can be 3 can be 2 or can be more.  Param0 and Param1 are not dates but day offsets from the base date.

**Comment by alexaverbuch** [comment]
@mkaufmann do you mind writing up a short description of the format of all parameter files?

**Comment by ArnauPrat** [comment]
@mkaufmann Then, do we need to change the query definition to accept a variable numbe of countries? or how it works?
Also, I think we should have dates as complete dates instead of offsets to be consistent

**Comment by mkaufmann** [comment]
The query definition is now updated in the wiki, added the endDate param during generation
