### ISSUE TITLE
generateparams error when scaling

### ISSUE THREAD

**Issue by MarcoLotz** [ldbc/ldbc_snb_datagen_spark#17]
Hi there,

I am trying to generate the 100GB dataset, but I am getting the following error:
I do have enough memory on the YARN containers (set even to 200GB each) and still have this error happening.

``` java
Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 296, in <module>
    sys.exit(main())
  File "paramgenerator/generateparams.py", line 152, in main
    selectedPersonParams[i] = discoverparams.generate(factors)
  File "/home/[user]/ldbc/ldbc_snb_datagen/paramgenerator/discoverparams.py", line 122, in generate
    params = len(factors[0]) -1
```

So far I was able to generate up to the 10GB one. Any ideas of what could this be?

**Comment by ArnauPrat** [comment]
The parameter generation is a step that starts just after the data generation has finished, and is done by a python script. So first, you must make sure the following:
- Data generation run successfuly. Make sure no errors were reported and that data is in your HDFS output folder.
- Make sure you are using python 2.6-7 

More questions. How many nodes does your cluster have? Is the dataset you are generating for SNB execution or for Graphalytics, or for anything else? Have you used any of the predefined scale factors?
Do not hesitate to contact me for further help :)
Regards,
Arnau

**Comment by MarcoLotz** [comment]
Hi @ArnauPrat. Thank you for your very fast answers in this and the other posts :)

I am rechecking, but I guess it was a glitch caused by no enough storage on HDFS (its folder was mounted in the wrong device). I am running in a quite unusual configuration, a single node with 4TB RAM and 80 cores - with yarn configured to take advantages of this. This may under perform in some moments due to the sequential batch jobs spilling data to disk, but just to generate the datasets should do (and still be faster than configuring the whole cluster).

I've python 2.7 right now, using SNB generator (not Graphalytics), with a 100 scale factor.

By the way, just wondering. The csv output is the one in the socialnetwork folder right? The hadoop one is just a tmp folder for in between jobs, correct?

Cheers,
Marco

**Comment by ArnauPrat** [comment]
Exactly, hadoop folder is just used to store temp files used during data generation. Most of them are deleted once they are not needed anymore, to reduce the amount of required space to operate. We also use it to store the factor files used later for parameter generation. 
Btw, I'd suggest you to use the BI branch, which should be faster and will be merged soon to the master one. It contains several optimizations, and it is preety stable right now.

Regards,
Arnau

**Comment by MarcoLotz** [comment]
Arnau, can you please provide me the exact python version that this datasets have been successfully generated? Have tried versions 2.7.6, 2.7.10 and 2.6.9 and I am getting python exceptions.

On 2.6.9 I am getting the following:
```python
^CTraceback (most recent call last):
  File "paramgenerator/generateparams.py", line 3, in <module>
    import readfactors
  File "/home/lotz/ldbc/ldbc_snb_datagen/paramgenerator/readfactors.py", line 7
    FACTOR_MAP = {value: key for (key, value) in enumerate(FACTORS)}
```

**Comment by ArnauPrat** [comment]
Hi Marco,

In my laptop I use 2.7.11. On a hadoop cluster I have 2.7.3, and I have 
successfully run parameter generation in a machine with 2.7.9

Can you confirm that data generation is working properly? Make sure you 
pull the latest changes from master branch before executing.

Regards,

Arnau

**Comment by MarcoLotz** [comment]
Thanks @ArnauPrat. Looks like lots of modifications came from the merge with bi branch :)

Will verify if it runs properly in a bit. Am installing python 2.7.3. By the way, there's a ":" file in the root folder that was probably left from the old bi branch

Cheers,
Marco

**Comment by MarcoLotz** [comment]
@ArnauPrat, I guess the BI merge added some unwanted files. I would suggest modifying the .run to remove the user specific part (first couple of lines). Is the heap option also user specific?

the zip part may require apt-get zip in Ubuntu 14.04 server, is the adding that section to the jar really required? I would suggest doing it with the jar command instead

i.e. 

```
jar -u file
```

Finally, just wondering. Is there any special reason for the project to be GPL3 instead of Apache-2 license?

**Comment by MarcoLotz** [comment]
Thanks for all the help @ArnauPrat, managed to get everything working :)

The problem wasn't the python version itself, but a HDFS misconfiguration that only shows up when generating more than 30GB. The python thing was happening because, even if the hadoop job fails, the python script would try to run and process the hadoop output data.

I would suggest adding a check for the hadoop command line return, before running the python scripts

``` bash
if [ $? -eq 0 ]
```

This should do it :)
