### ISSUE TITLE
substitution_parameters are not generated

### ISSUE THREAD

**Issue by arunram85** [ldbc/ldbc_snb_datagen_spark#175]
The script "run.sh" completes successfully  and also  outputs "Running Parameter Generation" at  the end but the substitution_parameters are not getting generated. The "params.ini" is same as " params-csv-basic.ini"

**Comment by szarnyasg** [comment]
Hello @arunram85,

for most use cases, I'd recommend switch over to the `stable` branch which is the stable version.
`dev` is under major refactoring (migrating from Hadoop to Spark) so it's expected to have a few hiccups.

Gabor

**Comment by arunram85** [comment]
Okay.. but I see that in dev branch the generated data-set is different. For example
1) There are new files like person_email_emailaddress.csv and person_speaks_language.csv 
2) The fields /columns positions are changed and in few files, new columns are added. It looks like, these changes are inline with dev(default branch) of https://github.com/ldbc/ldbc_snb_implementations.  So do is need to fall back to master branch even there.
3) Meanwhile, after running the "run.sh", when I examine the "parameters_interactive.log", I see below python errors:
loading input for parameter generation
Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 263, in <module>
    sys.exit(main())
  File "paramgenerator/generateparams.py", line 162, in main
    selectedCountryParams[i] = discoverparams.generate(factors, portion=0.1)
  File ".........../ldbc_snb_datagen/paramgenerator/discoverparams.py", line 121, in generate
    params = len(factors[0]) -1
IndexError: list index out of range
When I try to analyse, I see that at some stage , the list is empty ( i.e factor = [  ] )

**Comment by szarnyasg** [comment]
> So do is need to fall back to master branch even there.

Yes, that's what I'd recommend. Unless you want to use the delete generator (which we're still actively working on), the `master` branch is your best bet for all use cases.
