### ISSUE TITLE
Generating correct output for Interactive and BI workloads

### ISSUE THREAD

**Issue by jackwaudby** [ldbc/ldbc_snb_datagen_spark#176]
Both workloads comprise of a _bulkload_ component and an _update_ component. The desired output for each workload is given below.

### Interactive Workload
Select workload and number of concurrent update streams in `params.ini`:
`generator.mode:interactive`
`generator.mode.interactive.numUpdateStreams:X`

**Desired output:** 
- Bulkload data in `social_network/`
- `updateStreams_1.csv` ...` updateStreams_X.csv`

- [ ] Currently 4 file types produced during data generation: `insertStreams_*_person.csv` `insertStream_*_forum.csv` `deleteStreams_*_person.csv` `deleteStream_*_forum.csv`

(This was done because they were produced by separate generators.)

Note, events merged into a single stream, evenly spread across `updateStreams_*.csv` so operations are issued from streams concurrently.

### BI Workload
Select workload and number of update batches in `params.ini`:
`generator.mode:bi`
`generator.mode.bi.batches:X`

**Desired output:** 
- Bulkload data in `social_network/`
- `updateBatch_1.csv` ... `updateBatch_X.csv` (see GRADES paper: _"We consider the scenario of systems that query a static snapshot of the graph, and from time to time receive batch updates that must be incorporated into the database"_)

- [ ] How this is handled in Datagen has not been decided. One approach would be to generate the interactive `updateStreams_*.csv` then merge, sort and split in the required batches as an extra step. 

Note, timestamps within each batch should be ordered sequentially as well as across batches, all event timestamps in `updateBatch_1.csv`  < `updateBatch_2.csv`.

If an entity (e.g. a Comment) is both inserted and deleted in a batch, it is going to be part of the batch but the SUT is allowed to filter such updates (similarly to TPC-DS).

**Comment by jackwaudby** [comment]
#### Approach for turning entity lifespans #92 to bulkload component and update stream/batches component

Important simulation dates:
- `SS` = simulation start
- `BLT` = bulkload threshold
- `SE` = simulation end 

Each entity has: 
 - creation date `cd`
- deletion date `dd`
- explicit deletion flag `df`,  indicating the entity has been explicitly deleted during the simulation period. 

Data generation produces: 
- Bulkload component `BL`
- Update component `U`

When assigning an entity `e` to components there are 5 scenarios to consider:
1. Entity is created and deleted before the bulkload threshold -- `e.cd && e.dd < BLT`
      - Entity is not included in bulkload component nor update component. 
2. Entity is created before the bulkload threshold and is deleted after the bulkload threshold but before the simulation end -- `e.cd < BLT && BLT ≤ e.dd ≤ SE`
       - Entity is included in the bulkload data set, `e ∈ BL`
       - A deletion operation for `e` is included in the update component if the entity has been chosen for explicit deletion -- if `e.df = true` then `e ∈ U` else `e ∉ U`
3. Entity is created before the bulkload threshold and is deleted after the simulation end -- `e.cd < BLT && e.dd > SE`
        - Entity is included in the bulkload data set, `e ∈ BL`
4. Entity is created after the bulkload threshold and is deleted after the bulkload threshold but before the simulation end -- `e.cd ≥ BLT && BLT < e.dd ≤ SE`
        - An insert operation for `eᵢ` is included in the update component, `eᵢ ∈ U`
        - A deletion operation for `e_d` is included in the update component if the entity has been chosen for explicit deletion -- if `e.df = true` then `e_d ∈ U` else `e_d ∉ U`
5. Entity is created after the bulkload threshold and is deleted after the simulation end -- `e.cd ≥ BLT && e.dd > SE`
        - An insert operation for `eᵢ` is included in the update component, `eᵢ ∈ U`

**Comment by szarnyasg** [comment]
N.b. only deletions are cascading, "cascading inserts" do not exist.

**Comment by szarnyasg** [comment]
Note that the current version on the `dev` branch generates no updates/refreshes at all.

**Comment by jackwaudby** [comment]
Datagen v0.4.0 proposed design. 

It will support 3 modes, each having different output. 

1. **Interactive**, produces the data necessary for the interactive workload. Includes a set of bulk load csv files and a number of update streams, which contain only insert operations. 
2. **BI**, produces the data necessary for the business intelligence workload. Includes a set of bulk load csv files and a number of refresh batches, which contain insert and delete operations.
3. **Raw**, produces a fully dynamic graph.  Includes a set of bulk load csv files (covering whole simulation period), with each dynamic entity having creation and deletion date attributes serialized. This mode is not intended for use with any LDBC workload. 

To illustrate how each mode will be supported consider `Person`.

Firstly, the various Datagen modes `dg` are:
- `INT` = interactive
- `BI`= business intelligence 
- `RAW` = raw 

The various outputs Datagen produces are: 
- Bulkload files `BL`
- Update streams `U`
- Refresh batches `RB`

The important simulation dates are:
- `SS` = simulation start
- `BLT` = bulkload threshold
- `SE` = simulation end 
- `NC` = network collapse

Each `Person`  `p` entity has: 
 - creation date `cd`
- deletion date `dd`
- explicit deletion flag `df`, which indicates if the `Person` is to be explicitly deleted during the simulation period. 

### 1. Generation 

- If `dg == INT`,
  - generate creation date `p.cd`
  - set deletion date to network collapse `p.dd = NC`
- Else, 
  - generate creation date `p.cd`
  - If selected for explicit deletion (using the "if" in realism discussions),
    - set explicit deletion flag `p.df = T`
    - generate deletion date `p.dd` from interval determined by valid lifespan bounds (GRADES paper) and using the distribution from realism discussions (the "when")
  - Else,
    - set deletion date to upper bound valid lifespan bounds (GRADES paper), for `Person` this is network collaspe,`p.dd = NC`

### 2. Serialization  

- If `dg == RAW`,
  - serialize all generated `Person`s to bulkload files, include both creation date `p.cd` and deletion date `p.dd` as attributes. 
- Else if `dg == INT`,
  - If `Person` is created before bulkload threshold -- `p.cd < BLT`,
    - serialize `Person` to bulk load files,`p ∈ BL`
  - Else `Person` is created after bulkload threshold -- `p.cd >= BLT`,
    -  serialize insert operation for `Person` to update streams, `p ∈ U`
- Else (`dg == BI`), 
  - If `Person`  is created and deleted before the bulkload threshold -- `p.cd && p.dd < BLT` then,
      - `Person` is not included in bulkload files nor refresh batches files., i.e., it is not serialized 
  - Else if `Person` created before the bulkload threshold and is deleted after the bulkload threshold, but before the simulation end  -- `p.cd < BLT && BLT ≤ p.dd ≤ SE` then,
       -  serialize `Person` to bulk load files, `p ∈ BL`;  only includes creation date `p.cd` as attribute
       -  If the `Person` has been chosen for explicit deletion -- `p.df = true` then,
         - serialize a delete operation for `Person` to refresh batch, `p_d ∈ RB`
   - Else if `Person` is created before the bulkload threshold and is deleted after the simulation end -- `p.cd < BLT && p.dd > SE` then,
       - serialize `Person` to bulk load files, `p ∈ BL`;  only includes creation date `p.cd` as attribute
   - Else if `Person` is created after the bulkload threshold and is deleted after the bulkload threshold but before the simulation end -- `p.cd ≥ BLT && BLT < p.dd ≤ SE`
        - serialize an insert operation for `Person` to refresh batch, `p_i ∈ RB`
        -  If the `Person` has been chosen for explicit deletion -- `p.df = true` then,
          - serialize a delete operation for `Person` to refresh batch, `p_d ∈ RB`
   - Else `Person`  is created after the bulkload threshold and is deleted after the simulation end -- `p.cd ≥ BLT && p.dd > SE`
        - serialize an insert operation for `Person` to refresh batch, `p_i ∈ RB`

This same logic can be applied to any dynamic entity `e`.

**Comment by szarnyasg** [comment]
Raw mode should imply that bulk portion is 100%.

**Comment by jackwaudby** [comment]
After a quick experiment it seems `generator.mode:rawdata` already achieves this behaviour, with `generator.bulkLoadPortion` has no impact on the size of the generated data for this mode, which for SF1 weighs approx. 2.3GB. 

As a sanity check I ran `generator.mode:interactive` which has a half-baked implementation of the algorithm in the above comment, i.e., its doing some filtering based on creation dates, deletion dates, and the bulk-load threshold, this weighed approx. 0.65GB.

**Comment by szarnyasg** [comment]
This has been fixed by #243.
