### ISSUE TITLE
Compilation errors with run.sh

### ISSUE THREAD

**Issue by danhlephuoc** [ldbc/ldbc_snb_datagen_spark#18]
Hi,

I tried to compile the datagen with the run script run.sh, but I got the compilation error as bellow (I'm using : openjdk version "1.8.0_71")

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[13,66] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.distribution.utils.Bucket
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[30,39] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[19,14] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.distribution.utils.Bucket
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[24,19] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[24,68] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[31,35] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[134,19] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[134,69] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[141,40] cannot find symbol
  symbol:   class Pair
  location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[INFO] 12 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.680s
[INFO] Finished at: Mon Jul 25 17:00:25 CEST 2016
[INFO] Final Memory: 27M/332M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project ldbc_snb_datagen: Compilation failure: Compilation failure:
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[13,66] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.distribution.utils.Bucket
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[3,19] package javafx.util does not exist
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[30,39] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/utils/Bucket.java:[19,14] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.distribution.utils.Bucket
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[24,19] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[24,68] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/distribution/EmpiricalDistribution.java:[31,35] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.distribution.EmpiricalDistribution
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[134,19] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[134,69] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.BTERKnowsGenerator
[ERROR] /home/danh.lephuoc/ldbc/ldbc_snb_datagen/src/main/java/ldbc/snb/datagen/generator/BTERKnowsGenerator.java:[141,40] cannot find symbol
[ERROR] symbol:   class Pair
[ERROR] location: class ldbc.snb.datagen.generator.BTERKnowsGenerator

**Comment by ArnauPrat** [comment]
Hi @danhlephuoc 
Is this from a fresh clone? I've tested in two machines using both openjdk and java hotspot and I had no problems. If you rune mvn -DskipTests assembly:assembly, do you see the same problem?
Can you paste here your run.sh file?
Best,
Arnau

**Comment by danhlephuoc** [comment]
hi @ArnauPrat,

Yes, It's the fresh clone, I ran mvn -DskipTests assembly:assembly, but had the same problem.

Here is my run.sh config....

DEFAULT_HADOOP_HOME=/home/danh.lephuoc/hadoop/hadoop-2.6.0 
DEFAULT_LDBC_SNB_DATAGEN_HOME=/home/danh.lephuoc/ldbc/ldbc_snb_datagen 

HADOOP_HOME=${HADOOP_HOME:-$DEFAULT_HADOOP_HOME}
LDBC_SNB_DATAGEN_HOME=${LDBC_SNB_DATAGEN_HOME:-$DEFAULT_LDBC_SNB_DATAGEN_HOME}

export HADOOP_HOME
export LDBC_SNB_DATAGEN_HOME

mvn clean
mvn -DskipTests assembly:assembly

$HADOOP_HOME/bin/hadoop jar $LDBC_SNB_DATAGEN_HOME/target/ldbc_snb_datagen-0.2.5-jar-with-dependencies.jar $LDBC_SNB_DATAGEN_HOME/params.ini

rm -f m_personFactors_
rm -f .m_personFactors_
rm -f m_activityFactors_
rm -f .m_activityFactors_
rm -f m0friendList*
rm -f .m0friendList*

**Comment by ArnauPrat** [comment]
Arr you using ubuntu? It seems that Ubuntu doesn't include by default the
openjfx package integrated with openjdk by default. If thats the case, try
to sudo apt-get install openjfx

El 25 jul. 2016 10:32 p. m., "Danh Le Phuoc" notifications@github.com
escribió:

hi @ArnauPrat https://github.com/ArnauPrat,

Yes, It's the fresh clone, I ran mvn -DskipTests assembly:assembly, but had
the same problem.

Here is my run.sh config....

#!/bin/bash
DEFAULT_HADOOP_HOME=/home/danh.lephuoc/hadoop/hadoop-2.6.0 #change to your
hadoop folder
DEFAULT_LDBC_SNB_DATAGEN_HOME=/home/danh.lephuoc/ldbc/ldbc_snb_datagen
#change to your ldbc_socialnet_dbgen folder
allow overriding configuration from outside via environment variables i.e.
you can do HADOOP_HOME=/foo/bar LDBC_SNB_DATAGEN_HOME=/baz/quux
./run.sh instead
of changing the contents of this file

HADOOP_HOME=${HADOOP_HOME:-$DEFAULT_HADOOP_HOME}
LDBC_SNB_DATAGEN_HOME=${LDBC_SNB_DATAGEN_HOME:-$DEFAULT_LDBC_SNB_DATAGEN_HOME}

export HADOOP_HOME
export LDBC_SNB_DATAGEN_HOME

mvn clean
mvn -DskipTests assembly:assembly

$HADOOP_HOME/bin/hadoop jar
$LDBC_SNB_DATAGEN_HOME/target/ldbc_snb_datagen-0.2.5-jar-with-dependencies.jar
$LDBC_SNB_DATAGEN_HOME/params.ini

rm -f m_personFactors_
rm -f .m_personFactors_
rm -f m_activityFactors_
rm -f .m_activityFactors_
rm -f m0friendList*
rm -f .m0friendList*

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/ldbc/ldbc_snb_datagen/issues/18#issuecomment-235075584,
or mute the thread

**Comment by danhlephuoc** [comment]
@ArnauPrat: I used Centos, but then I tried to do the same with Ubuntu I have following errors:

java.lang.Exception: org.apache.hadoop.mapreduce.task.reduce.Shuffle$ShuffleError: error in shuffle in localfetcher
#19
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: org.apache.hadoop.mapreduce.task.reduce.Shuffle$ShuffleError: error in shuffle in localfetcher#19
        at org.apache.hadoop.mapreduce.task.reduce.Shuffle.run(Shuffle.java:134)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:376)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.apache.hadoop.io.BoundedByteArrayOutputStream.<init>(BoundedByteArrayOutputStream.java:56)
        at org.apache.hadoop.io.BoundedByteArrayOutputStream.<init>(BoundedByteArrayOutputStream.java:46)
        at org.apache.hadoop.mapreduce.task.reduce.InMemoryMapOutput.<init>(InMemoryMapOutput.java:63)
        at org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl.unconditionalReserve(MergeManagerImpl.java:304)
        at org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl.reserve(MergeManagerImpl.java:294)
        at org.apache.hadoop.mapreduce.task.reduce.LocalFetcher.copyMapOutput(LocalFetcher.java:131)
        at org.apache.hadoop.mapreduce.task.reduce.LocalFetcher.doCopy(LocalFetcher.java:102)
        at org.apache.hadoop.mapreduce.task.reduce.LocalFetcher.run(LocalFetcher.java:85)
16/08/10 23:24:58 INFO mapreduce.Job: Job job_local1613409847_0019 failed with state FAILED due to: NA
16/08/10 23:24:58 INFO mapreduce.Job: Counters: 20
        File System Counters
                FILE: Number of bytes read=35296849725
                FILE: Number of bytes written=44839811789
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
        Map-Reduce Framework
                Map input records=3338809
                Map output records=3338809
                Map output bytes=362538740
                Map output materialized bytes=369723873
                Input split bytes=1608
                Combine input records=0
                Spilled Records=3338809
~  
                Failed Shuffles=0
                Merged Map outputs=0
                GC time elapsed (ms)=30
                CPU time spent (ms)=0
                Physical memory (bytes) snapshot=0
                Virtual memory (bytes) snapshot=0
                Total committed heap usage (bytes)=6278873088
        File Input Format Counters 
                Bytes Read=396268923
Error during execution
null
java.lang.Exception
        at ldbc.snb.datagen.hadoop.HadoopUpdateStreamSorterAndSerializer.run(HadoopUpdateStreamSorterAndSerializer.
java:107)
        at ldbc.snb.datagen.generator.LDBCDatagen.runGenerateJob(LDBCDatagen.java:226)
        at ldbc.snb.datagen.generator.LDBCDatagen.main(LDBCDatagen.java:375)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by tomersagi** [comment]
@ArnauPrat this is an issue in Debian as well. Why do we need this dependency at all?

Lets replace it with Apache Commons [Pair](http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/tuple/Pair.html)

**Comment by ArnauPrat** [comment]
In principle the dependency was removed.
Closing.
