### ISSUE TITLE
[suggestion] add more properties to the edges/relationship

### ISSUE THREAD

**Issue by whitewum** [ldbc/ldbc_snb_datagen_spark#180]
I notice that the LDBC nodes/vertices' have many properties (e.g., Person, Message).

But the edge/relationship 's properties are rare (I can only find DateTime as property)

I think the number and size of the properties of edges will affect graph transversal speed.

Can you consider adding more properties to edges?

**Comment by szarnyasg** [comment]
Hi @whitewum, 

we don't plan to introduce substantial changes to the graph schema. Therefore, introducing edge properties is currently out of scope.
That said, we have recently introduced lifespan attributes (creation date and deletion date) for all dynamic edges. You could easily 'slice and dice' these attributes (e.g. `year` -> int32, `month` -> string, `isWeekend` -> boolean) to get some edge properties.
But we do not plan to incorporate such edge properties in the queries of the SNB benchmarks.

Gabor
