### ISSUE TITLE
generating messages between user

### ISSUE THREAD

**Issue by drkwolf** [ldbc/ldbc_snb_datagen_spark#19]
Hi there,
i'm interested in the message frequency between users and i am wondering if there's any plan to implement this feature

**Comment by ArnauPrat** [comment]
Hi @drkwolf 
Could you elaborate more on your request please? Users do no exchange messages privately but comment on other users's wall or on groups. The amount of messages issued per user per month can be controlled by means of an iternal parameter. Maybe I can tell you how to do so if this is what you need.

**Comment by drkwolf** [comment]
private messages is available on all social media platform, actually  we have a project in which we have to propose a privacy model to social media users based on fuzzy clustering and  private messaging frequency attribute between users is important for us.

**Comment by ArnauPrat** [comment]
Although I understand your request, supporting modeling private messages between users is not a priority for the LDBC Social Network Benchmark right now. However, I can give you some guidelines though in modifying the generator to add this feature if you want.
