### ISSUE TITLE
The max length of the type string is not enforced

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_datagen_spark#20]
Hi,

The [benchmark specification](https://github.com/ldbc/ldbc_snb_docs/blob/master/LDBC_SNB_v0.2.3.pdf) on pp.12 defines the type string as a variable length text of size 40 unicode characters. However it appears that at least using the SNB generator with SF1, several strings have longer lengths. For instance:
* forum.name:
Failed to import table line 316 field title 'varchar(40)' expected in 'Group for Agatha_Christie in Newcastle_upon_Tyne' 
Failed to import table line 13860 field title 'varchar(60)' expected in 'Group for Titanic:_Music_from_the_Motion_Picture in Shah_Alam' 
* organisation.name:
Failed to import table line 172 field name 'varchar(40)' expected in 'SAVAG__Sociedade_Anônima_Viação_Aérea_Gaúcha'
Failed to import table line 2705 field name 'varchar(80)' expected in 'École_Nationale_Supérieure_d'Électronique,_d'Électrotechnique,_d'Informatique,_d'Hydraulique_et_des_Télécommunications' 
* person.email:
Failed to import table line 640 field email 'varchar(40)' expected in 'Charles28587302325988@certifiedbitches.com'
* place.name:
 Failed to import table line 760 field name 'varchar(40)' expected in 'http://maps.google.com/maps?ll=25.530889,69.017306&spn=0.01,0.01&t=m&q=25.530889,69.017306'
* tag.name:
Failed to import table line 919 field name 'varchar(40)' expected in 'Princess_Victoria_of_Saxe-Coburg-Saalfeld'
Failed to import table line 15618 field name 'varchar(80)' expected in 'Children_of_Nuggets:_Original_Artyfacts_from_the_Second_Psychedelic_Era,_1976–1995'

Am I misinterpreting the definition or either the specification or the datagen implementation is in defect?

Thanks,
Dean

**Comment by ArnauPrat** [comment]
Thanks @whatsthecraic 
You are certainly right, these lengths are not currently enforced. I'll raise the issue to our next internal meeting and work on the fix ASAP.
Best,
Arnau

**Comment by ArnauPrat** [comment]
Hi @whatsthecraic 

We've added a new type "Long String" with 256 characters long (specification is changed accordingly, in the source files. Changes will be visible in the next release). Additionally, I've updated Datagen to clamp strings that are larger than they should be. I've also added tests for that. 
The changes have been pushed to master branch.

**Comment by szarnyasg** [comment]
This has indeed been fixed.
