### ISSUE TITLE
dataset can be found in hdfs,but none flush to the disk 

### ISSUE THREAD

**Issue by rainmaple** [ldbc/ldbc_snb_datagen_spark#202]
`ldbc.snb.datagen.generator.scaleFactor:snb.interactive.1

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvMergeForeignDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvMergeForeignDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvMergeForeignStaticSerializer
ldbc.snb.datagen.util.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-dd' 'HH:mm:ss
ldbc.snb.datagen.serializer.outputDir:/data2/ldbc_dataset/sf1/
ldbc.snb.datagen.serializer.updateStreams:false
`

this is my configuration file -- params.ini , which sets the output file location is `/data2/ldbc_dataset/sf1/` , but when the run.sh script excution have finished successfully, i could not find any localfile in location i set before. The file generated by the program in hdfs can be seen.

**Comment by szarnyasg** [comment]
@rainmaple are you using the `dev` or the `stable` branch? Which benchmark do you intend to implement?

Cheers,
Gabor

**Comment by rainmaple** [comment]
The branch i choosed was the stable. I found the solution but still confuse with the problem. The hadoop version i used to run the benchmark is the 2.9.2. When i turn to 3.2.1, file in hdfs can be flushed to the disk successfully. Is this version of the hadoop mandatory?  Or you'd better add the bug info about the hadoop version log for the sake of scientific procedure.

**Comment by szarnyasg** [comment]
@rainmaple I was unaware of this incompatibility, thanks for pointing it out. I added a note in the README of the `stable` branch that encourages users to use Hadoop v3.2.1.
