### ISSUE TITLE
Renaming generated columns

### ISSUE THREAD

**Issue by kubajal** [ldbc/ldbc_snb_datagen_spark#203]
Hi,
is there a way to configure column names in the generated .csv file _before_ actually generating the data? Imho column naming is currently quite unfortunate, e.g. `comment_replyOf_comment_0_0.csv` has two columns, both named `Comment.id` which causes problems when loading to a graph database or an analytics tool because the colum names are not unique. Additionally, It would probably be better to use some other separator than dot ('.') in column names because it is reserved in some technologies (like in `Neo4j` which it is a field accessor and causes clashes when creating nodes). Is it possible to replace dots in the column names with underscores or a dashes instead?

Jakub

**Comment by kubajal** [comment]
I looked into the code and as far as I can see [this is the relevant code for CSV column naming](https://github.com/ldbc/ldbc_snb_datagen/blob/dev/src/main/java/ldbc/snb/datagen/serializer/snb/csv/dynamicserializer/activity/CsvBasicDynamicActivitySerializer.java#L71) (I am not sure if that is the only relevant place). This code could probably be refactored so that it reads e.g. `columns.COMMENT_REPLYOF_COMMENT_1=id_1` and `columns.COMMENT_REPLYOF_COMMENT_2=id_2` from `params.ini` first and when the column names are not available there then sets the default value (such as `Comment.id`).

**Comment by szarnyasg** [comment]
@kubajal I agree that the default column names are not the best. In the Neo4j implementation, I just change the [headers](https://github.com/ldbc/ldbc_snb_implementations/blob/3f505b53650f16a4ac42cb565ccd0e5f7bee4861/cypher/scripts/headers.txt) with a [combination of `tail` and `cat`](https://github.com/ldbc/ldbc_snb_implementations/blob/dev/cypher/scripts/convert-csvs.sh#L13) (I've also tried `sed` and `ed` but neither worked as well as the current solution.)
Refactoring this is definitely possible, particularly on the `dev` branch/Spark implementation.

**Comment by szarnyasg** [comment]
I attempted to fix this with https://github.com/ldbc/ldbc_snb_datagen/pull/210/commits/d85069187be356a231ee5f9bcf6c0a11250d62cb. This affects the person-knows-person edges and the comment-reply-message (post|comment) edges.
@kubajal Let me know if you like the proposed header names.

**Comment by kubajal** [comment]
Hi @szarnyasg,
thanks for feedback. Yes, to me it does look ok - the column names are not duplicated. 
But perhaps they could be even more meaningful? I was thinking of something like renaming
`Person1.id` and `Person2.id` in `CsvCompositeMergeForeignDynamicPersonSerializer.java` to `Person.source.id` and `Person.target.id`. As far as I see there is the assumption everywhere, that the left column is the "source" and the right column is the "target". Making the names of the columns reflect that could be more intuitive.

**Comment by szarnyasg** [comment]
For `Person-knows-Person`, I'd like to avoid `source` and `target` as users might associate those with a directed edge. Hence, I'd rather go for the non-descriptive `Person1.id`, `Person2.id` names.
