### ISSUE TITLE
Some persons do not have an email address

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_datagen_spark#21]
Hi,

At least for the generated dataset with SF1, some persons do not have an email address. For instance, from the output of the CSVMergeForeign serializer:
```
# awk 'BEGIN { FS= "|" }; $1 == 8698' person_0_0.csv
8698|Chen|Liu|female|1982-05-29|2010-02-21T09:44:41.479+0000|14.103.81.196|Firefox|432
# awk 'BEGIN { FS= "|" }; $1 == 8698' person_email_emailaddress_0_0.csv 
... no result ...
```
The [specification](https://github.com/ldbc/ldbc_snb_docs/blob/master/LDBC_SNB_v0.2.3.pdf) describes on pp. 16 that the attribute email of a Person consists of 1 or more strings.

Is this a discrepancy between the specification and the actual behaviour of the datagen tool?

**Comment by ArnauPrat** [comment]
Hi @whatsthecraic 
Thanks for reporting this. This is indeed an error in Datagen. I'll add a test for it and fix the error.
Best,
Arnau

**Comment by ArnauPrat** [comment]
I've fixed the bug and added a test for that. Changes are pushed to master branch.
