### ISSUE TITLE
Question on date format in substitution params

### ISSUE THREAD

**Issue by djnakabaale** [ldbc/ldbc_snb_datagen_spark#221]
Hi, 
I would like to get more context on the date format generated in the substitution parameters by the datagen.
First I would like reference issue #86. @szarnyasg mentions it can be configured in params.ini.
I have tried this and I am still getting the same formats.

I would like to generate a dataset for postgres and my params.ini looks like this:
```
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.10

ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvMergeForeignDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvMergeForeignDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvMergeForeignStaticSerializer
ldbc.snb.datagen.serializer.formatter.StringDateFormatter.dateTimeFormat:yyyy-MM-ddTHH:mm:ss.SSS+00:00
```

here are the first 2 rows and 2 cols in the social/dynamic/comment_0_0-postgres.csv
```
id||creationDate
1236950581249||2011-08-17T14:26:59.961+0000|
```

interactive-complex-3.sql queries against the _creationDate_ field as _startDate_

here are the first 2 rows and 2 cols in the substitution/interactive_1_param.txt
```
personId|startDate|
17592186055119|1306886400000|
```

I would understand what the date format in the substitution parameter file is and if possible how I convert it to be the same as the one in the csv file.

Thanks.

**Comment by szarnyasg** [comment]
Hi @dmj2x,

I assume you are on the `stable` branch (with the Hadoop-based generator).

> here are the first 2 rows and 2 cols in the social/dynamic/comment_0_0-postgres.csv
Based on the filename, this is your Postgres file, converted with the [script in the implementations repository](https://github.com/ldbc/ldbc_snb_implementations/blob/dev/postgres/load-scripts/load.sh). 

After you have regenerated the CSV with Datagen, check the `comment_0_0.csv` file. If it looks good, convert it using the script. I generating some data with your configuration (sized down to SF 0.1) and here's how it looks like:

```
$ head -n 2 social_network/dynamic/comment_0_0.csv
618475290625|2011-08-17T14:26:59.961+0000|46.16.217.105|Chrome|yes|3|10995116278291|50|618475290624|
```

The dates are in substitution parameters are epochs, to be interpreted with the GMT+0 time zone. For the example you quoted, https://www.epochconverter.com/ gives me "Wednesday, June 1, 2011 12:00:00 AM".

The conversion of substitution parameters is done in the Java code of the client implementations, see:
https://github.com/ldbc/ldbc_snb_implementations/blob/e9cf1bf8018e4414170629432221f34c6f4e14fb/common/src/main/java/com/ldbc/impls/workloads/ldbc/snb/converter/Converter.java#L15-L31

**Comment by djnakabaale** [comment]
Hi @szarnyasg,

Thanks for getting back to me.
Just a minor not to your above response, I am using the stable branch and the docker image build. I'm not sure if that changes a thing. I am still working through conversion.

**Comment by szarnyasg** [comment]
> I am using the stable branch and the docker image build.

Yeah, those should be good. Let me know what you find.

**Comment by djnakabaale** [comment]
> Hi @szarnyasg ,
> 
> After you have regenerated the CSV with Datagen, check the `comment_0_0.csv` file. If it looks good, convert it using the script. I generating some data with your configuration (sized down to SF 0.1) and here's how it looks like:
> 
> ```
> $ head -n 2 social_network/dynamic/comment_0_0.csv
> 618475290625|2011-08-17T14:26:59.961+0000|46.16.217.105|Chrome|yes|3|10995116278291|50|618475290624|
> ```
> 
> I generated a CSV with SF1
>```
> head -n 2 social_network/dynamic/comment_0_0.csv 
> 1236950581249|2011-08-17T14:26:59.961+0000|92.39.58.88|Chrome|yes|3|10995116284808|86|1236950581248|
>```
>and 
>```
> head -n 2 social_network/dynamic/comment_0_0-postgres.csv
> id||creationDate|locationIP|browserUsed||content|length|creator|place||replyOfPostreplyOfComment
> 1236950581249||2011-08-17T14:26:59.961+0000|92.39.58.88|Chrome||yes|3|10995116284808|86||1236950581248
>```

> Here is a bash command I use to make date conversion:
`TZ=GMT date -u -j -r $((dateVal/1000)) '+%Y-%m-%d %H:%M:%S.%S'` However this command generates dates without actual time with time as 00:00:00.00.


> Here is how dates look like in the message/comment table 
>```
> ldbc=# select m_messageid, m_creatorid, m_creationdate from message limit 5;
> m_messageid  | m_creatorid |     m_creationdate      
> ---------------+-------------+-------------------------
> 1236950581248 |         933 | 2011-08-17 06:05:40.595
>             3 |         933 | 2010-02-14 20:30:21.451
> 2061584302084 |         933 | 2012-07-20 03:48:53.147
> 1649267441688 |         933 | 2012-02-27 03:45:05.655
> 1786706395168 |         933 | 2012-03-21 16:21:11.935
>```

My question is, how is the conversion handled in the implementations to generate dates with actual (differing) times?

**Comment by szarnyasg** [comment]
> My question is, how is the conversion handled in the implementations to generate dates with differing times?

I'm not sure what you mean exactly. Can you please clarify?

When using the substitution parameters, we turn them to a datetimes string (which can be substituted in the Postgres query) using Java 8's datetime library:

```java
    protected final ZoneId GMT = ZoneId.of("GMT");
    final String DATAGEN_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'+0000'";
    final DateTimeFormatter dfGeneric = DateTimeFormatter.ofPattern(DATAGEN_FORMAT).withZone(GMT);

    /**
     * Converts epoch seconds to a date to the format of the converter (e.g. PostgreSQL-style timestamps).
     *
     * @param timestamp
     * @return
     */
    public String convertDateTime(long timestamp) {
        return convertDateTime(new Date(timestamp));
    }

    public String convertDateTime(Date date) {
        return "'" + dfGeneric.format(date.toInstant()) + "'";
    }
```

These methods are used in the `QueryStore` class and its subclasses such as `PostgresQueryStore`:

https://github.com/ldbc/ldbc_snb_implementations/blob/e9cf1bf8018e4414170629432221f34c6f4e14fb/common/src/main/java/com/ldbc/impls/workloads/ldbc/snb/QueryStore.java#L176-L181

```java
    public String getQuery2(LdbcQuery2 operation) {
        return prepare(QueryType.InteractiveComplexQuery2, new ImmutableMap.Builder<String, String>()
                .put("personId", getConverter().convertId(operation.personId()))
                .put("maxDate", getConverter().convertDateTime(operation.maxDate()))
                .build());
    }
```

The conversion from the epoch value to the datetime value happens at a different sport for Interactive and BI.

* For Interactive, it's a `Date` object: https://github.com/ldbc/ldbc_snb_driver/blob/dev/src/main/java/com/ldbc/driver/workloads/ldbc/snb/interactive/LdbcQuery2.java#L28
* For BI, it's an epoch: https://github.com/ldbc/ldbc_snb_driver/blob/dev/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery1PostingSummary.java#L16

This is something that should be unified in the driver. Currently, the implementations handle this.

**Comment by djnakabaale** [comment]
> I'm not sure what you mean exactly. Can you please clarify?
> 
> Here are the first 10 and the header in the interactive_2_param.txt file
>```
> personId|maxDate
> 17592186052613|1354060800000
> 4398046514238|1354060800000
> 4398046513906|1323561600000
> 10995116287298|1323648000000
> 6597069777312|1347494400000
> 24189255819351|1330300800000
> 17592186045019|1334707200000
> 10976|1334448000000
> 15393162792273|1354060800000
>```
>
> and below when converted to human readable time
>```
> Epoch date 	Human-readable date (GMT) 
> 1354060800	2012-11-28 00:00:00
> 1354060800	2012-11-28 00:00:00
> 1323561600	2011-12-11 00:00:00
> 1323648000	2011-12-12 00:00:00
> 1347494400	2012-09-13 00:00:00
> 1330300800	2012-02-27 00:00:00
> 1334707200	2012-04-18 00:00:00
> 1334448000	2012-04-15 00:00:00
>```
>
> when I query the message table to check whether there's a date with such a time and turns out there's not.
>```
> ldbc=# select m_messageid, m_creatorid, m_creationdate from message where m_creationdate::text like '%00:00:00.000%';
> m_messageid | m_creatorid | m_creationdate 
> -------------+-------------+----------------
> (0 rows)
>```

> There are 98 rows in the interactive_2_param.txt (excluding the header). This means for all these params, there will be no query results. Is this an expected outcome?

**Comment by szarnyasg** [comment]
> There are 98 rows in the interactive_2_param.txt (excluding the header). This means for all these params, there will be no query results. Is this an expected outcome?

In Interactive, it is guaranteed that there's always an output of the query. (This is also a design goal in BI but that might have more bugs.)

Interactive [Q2](https://ldbc.github.io/ldbc_snb_docs_snapshot/interactive-complex-read-02.pdf) prescribes `creationDate < $maxDate` not equivalence. In your SQL query, try `m_creationDate::text < :maxDate`. Lexicographical ordering [works for e.g. ISO 8601 dates](https://stackoverflow.com/questions/36922398/what-is-the-appropriate-date-formatting-so-the-lexicographic-ordering-is-the-sam). Later, you might want to use SQL's date type.

**Comment by djnakabaale** [comment]
Thanks @szarnyasg! I found the issue, it was in my script.
