### ISSUE TITLE
Characterize the branching factor of messages

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#232]
in the thread tree.

**Comment by szarnyasg** [comment]
With the data loaded to Neo4j, it's easy to compute the branching factor:

```
MATCH (m:Message)<-[:REPLY_OF]-(c:Comment)
WITH m, count(c) AS replies
RETURN avg(replies)
```

For SF1, it's `3.22`.

Other statistics:

```
MATCH (m:Person)-[:KNOWS]-(f:Person)
WITH m, count(f) AS friends
RETURN avg(friends)
```
-> `39.42`

```
MATCH (tc:TagClass)<-[:IS_SUBCLASS_OF]-(stc:TagClass)
WITH tc, count(stc) AS subTagClasses
RETURN avg(subTagClasses)
```
-> `3.68`

**Comment by jackwaudby** [comment]
The comment generation process works by first choosing the number of comments C in the tree uniformly from the range [0,20]. The post (root) message is then entered into a list of parent candidates. Then, C comments are generated, for each comment, a random parent is selected from the parent candidates, if the comment is not a "short" comment, e.g., thanks, ok, (1/3 of all comments are short) then that comment is added to the pool of parent candidates for the next iteration.

**Comment by szarnyasg** [comment]
See also PR #235.

**Comment by szarnyasg** [comment]
This is now (superficially) documented in our slideshows.
