### ISSUE TITLE
BI substitution parameter generator

### ISSUE THREAD

**Issue by djnakabaale** [ldbc/ldbc_snb_datagen_spark#236]
In one of the responses on issue #132, @szarnyasg you said:
> Paramgen always generates the same number of parameter, this is something that currently cannot be tuned.
> Paramgen currently is also rather slow - this is something we're looking in the near future. For the time being, I have the parameters pre-generated. E.g. SF1 is here: https://www.dropbox.com/s/iipb1412kh3szen/sf1.zip?dl=0
(https://github.com/ldbc/ldbc_snb_datagen/issues/132#issuecomment-611122148 )

I would like to inquire if this is still the case or if there is there a way to manage the number of substitution parameters generated? 
I am currently with *scale factor 30* on branch *v0.3.3* and it generates *1655* substitution params. I would like to be able to generate a much smaller number.

**Comment by szarnyasg** [comment]
Hi @dmj2x, this is still an issue and being worked on (but always get preempted by some other task...).

**Comment by djnakabaale** [comment]
Oh okay, I appreciate your quick response.

**Comment by szarnyasg** [comment]
Continued in #318
