### ISSUE TITLE
Understanding knows edge deletion behaviour at large scale factors

### ISSUE THREAD

**Issue by jackwaudby** [ldbc/ldbc_snb_datagen_spark#239]
The probability a given knows edge is deleted is dependent on the similarity [0,1] between two persons, with lower similarity indicating a higher chance that two persons "unfriend" each other (Myers and Leskovec, 2014). 

The target proportion of knows edges that are deleted across the simulation period is 5%. Current analysis has been performed on SF1 finding the average similarity weight between friends is 0.922, thus a simplistic approach to assign deletion probabilities is if the similarity weight is less than 0.922, assigns 0.075, else assign 0.025, which will average at 0.05. 

Ideally a more granular distribution can be used, however, it is unclear how the average similarity weight will change at higher scale factors. One hypothesis is persons will have more friends, thus, the average similarity weight will decrease. This will result in a increase in delete events and hence deletions operations as the scale factor increases. In order to keep knows delete operations consistent (at 5%) across SF some scaling will be needed. This will need to be investigated empirically.

**Comment by dszakallas** [comment]
> Current analysis has been performed on SF1 finding the average similarity weight between friends is 0.922, thus a simplistic approach to assign deletion probabilities is if the similarity weight is less than 0.922, assigns 0.075, else assign 0.025, which will average at 0.05.

We would need the median weight for that math to work out don't we?

**Comment by szarnyasg** [comment]
```console
$ wc -l initial_snapshot/dynamic/person_knows_person/*.csv
369 206
$ wc -l inserts/dynamic/person_knows_person/*/*.csv
10 122 668 total
$ wc -l deletes/dynamic/person_knows_person/*/*.csv
958 559 total
```

Interestingly, the dates are correct but the activity network is *very heavily* skewed towards the last 10% of the network's lifecycle.

**Comment by szarnyasg** [comment]
@jackwaudby Is there anything to add to this issue or shall we close it?

**Comment by jackwaudby** [comment]
Think we can close this issue.
