### ISSUE TITLE
Broken link for workload generator

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#24]
The link for the **ldbc_socialnet_qgen** is broken in the [wiki](https://github.com/ldbc/ldbc_snb_datagen/wiki). Does the workload generator still exist as a separate component?

**Comment by ArnauPrat** [comment]
Hi @szarnyasg 

This ldbc_socialnet_qgen is something that is no longer used (from long time ago). I acutally didn't know about the page you linked. Currently, parameters for the queries (the workload) are generated by datagen project itsef, at the end of the data generation. These can be found at the substitution_parameters folder once the execution is finished.
Best,
Arnau

**Comment by szarnyasg** [comment]
Hi @ArnauPrat 

thanks for the immediate reply. I updated the wiki page on the [configuration](https://github.com/ldbc/ldbc_snb_datagen/wiki/Configuration/_history), please check if my changes are correct. I removed the outdated shell script, which did not work - it even failed on the Maven tests with the following error:

```
ERROR PASSING TEST ID UNIQUENESS FOR FILE ./test_data
```

Running the `run.sh` in the repository works better, but also fails after some time with the following exception:

```
Error during execution
null
java.lang.Exception
	at ldbc.snb.datagen.hadoop.HadoopUpdateStreamSorterAndSerializer.run(HadoopUpdateStreamSorterAndSerializer.java:107)
	at ldbc.snb.datagen.generator.LDBCDatagen.runGenerateJob(LDBCDatagen.java:226)
	at ldbc.snb.datagen.generator.LDBCDatagen.main(LDBCDatagen.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```

**Comment by szarnyasg** [comment]
Okay, I scrolled back a bit and it seems it runs out of memory: https://gist.github.com/szarnyasg/ec4d4821df6840d62f41ddb459bf57d8#file-gistfile1-txt-L2426

**Comment by ArnauPrat** [comment]
You probably need to increase your heap size by adding the proper java option to HADOOP_OPTS variable. You can do this in the run.sh or in hadoop_env.sh file under /etc/hadoop.
Hope this helps.

PD: Sorry about the faulty error reporting. This is something that must be definitely fixed. I have to figure out how to capture the exceptions produced in workers and print the result in the master, without having to look neither at the std output nor the log files.

**Comment by szarnyasg** [comment]
Thanks, running the following command resolved the memory issues:
```
export HADOOP_CLIENT_OPTS="-Xmx12G"
```

**Comment by ArnauPrat** [comment]
Great!
