### ISSUE TITLE
Missing run.sh

### ISSUE THREAD

**Issue by Arun-George-Zachariah** [ldbc/ldbc_snb_datagen_spark#256]
Hi, 

The readme mentions executing `tools/run.sh` (https://github.com/ldbc/ldbc_snb_datagen#running-locally). But there is no `run.sh` present. Could you kindly upload the appropriate `run.sh`?

**Comment by dszakallas** [comment]
Hi  @Arun-George-Zachariah I forgot to update the doc, you should use `tools/run.py`
