### ISSUE TITLE
Serialize generated data to multiple output formats

### ISSUE THREAD

**Issue by javaprog** [ldbc/ldbc_snb_datagen_spark#26]
For a complex query where we are not sure if the results are correct, we would like to be able to verify it against another system. If the system under test can only understand one output format of the data generator (e.g. RDF) and the verification system only supports another output format (e.g. CSV), we would have to convert the generated data. Howerver, it should be easier to simply stream the generated data through multiple serializers in order to produce multiple output formats.

**Comment by szarnyasg** [comment]
The idea proposed here to allow users to register multiple serializers so that we can skip multiple Hadoop runs. This would indeed be more efficient but this is not a serious limitation, therefore I'm closing this now as a wontfix.
