### ISSUE TITLE
Publish small datasets as tar.gz or .zip

### ISSUE THREAD

**Issue by kubajal** [ldbc/ldbc_snb_datagen_spark#264]
Hi,
could you please publish here: http://ldbc.github.io/ldbc_snb_datagen/ small datasets (those that are smaller than 300MB) packed as .tar.gz or .zip?
Currently, each dataset is available as a bunch of .csv files. It would be nice to have them available as .tar files which could be easier accessed using `wget`.
Best regards,
Jakub

**Comment by szarnyasg** [comment]
@kubajal Good question... I don't think it would work well as part of the CI/CD process to publish data sets in the range of ~100MB for every commit.

Putting the files in an archive could be easily done for the current (very small) data sets.

**Comment by szarnyasg** [comment]
I added steps to compress the files into archives. However, this will necessitate a few changes with the deployment: as compressed files do not 'diff' nicely, the history of the `gh-pages` branch will consume a lot of space.

**Comment by kubajal** [comment]
Thanks!
