### ISSUE TITLE
Making java 1.7 compatible

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_datagen_spark#27]
Related to https://github.com/ldbc/ldbc_snb_datagen/commit/833868f7565d19c9e6ce9dc65febd963411d7f30, List#sort is still [Java 1.8](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#sort-java.util.Comparator-). For some reason the error is not caught by the Java compiler, but I assure you a JVM based on 1.7 catches it strong & clear. Attached a tentative patch using Collections#sort
[diff.txt](https://github.com/ldbc/ldbc_snb_datagen/files/844928/diff.txt)

**Comment by szarnyasg** [comment]
Thank you. I applied your patch in #28.
