### ISSUE TITLE
(De)serialization of timestamps is very slow

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#271]
This causes considerable slowdown (e.g. 2x slow).

A potential workaround would be using epochs (as everything is GMT) which are faster to read/parse/compare.

**Comment by dszakallas** [comment]
Cannot do much about it, per requirements, we have to use that given date format in raw files. However if we map the column to date right away, we could work with it on later stages without having to parse them on-demand
