### ISSUE TITLE
Introduce configuration language

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#272]
Configuration should include the following:

Generator properties:
- scale factor
- block size
- number of persons
- number of years
- start year

Serializer properties:
- initial data set threshold (e.g. 90% goes to the "initial snapshot" data set)
- exploding attributes (Composite attributes vs. Singular attributes)
- exploding edges (Merged FK vs. Projected FK)
- batch size (e.g. daily)
- timestamp format
- mode (Raw/BI/Interactive)
- generate headers or not

**Comment by dszakallas** [comment]
Generator properties continue to be configurable with the parameter file with minor changes only.
The following serializer properties are not implemented yet:
 1. timestamp format (related to #271)
 2. generate headers or not

**Comment by dszakallas** [comment]
You can configure the headers with #277. The timestamp format should be done as part of #271. I am closing this issue.
