### ISSUE TITLE
numPartitions configuration is not used

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#273]
`numPartitions` is not used. It's accessed in https://github.com/ldbc/ldbc_snb_datagen/blob/294f2c6ed28d7d130689c52c8dc422dfdf94ce2d/src/main/java/ldbc/snb/datagen/hadoop/writer/HdfsWriter.java#L60-L69 but it's only set to 1.

**Comment by dszakallas** [comment]
We use it for adaptive partitioning now
