### ISSUE TITLE
Do not store raw in non-raw mode

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#286]
When generating the data in e.g. BI mode, the `raw` directory is kept, effectively doubling the size of the generated data sets.

**Comment by dszakallas** [comment]
Isn't this resolved by #327?

**Comment by szarnyasg** [comment]
On S3, yes, but locally the `raw` directory is kept at the end of the generation.
```bash
du -hd0 out/graphs/csv/*
3.8M	out/graphs/csv/interactive
3.7M	out/graphs/csv/raw
```
It's arguable whether this should be the case. I don't mind keeping it -- even if we delete it, it will not reduce the maximum disk usage during generation.

**Comment by dszakallas** [comment]
Unfortunately we need that during generation now, until we come up something better than the two-stage generation phase.
