### ISSUE TITLE
Allow configurable data set compression

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#289]
There are multiple issues with compression:
* ~it only works for static data sets~
* ~it's not accessible through a command-line/config file switch~
* it uses GZIP (instead of ZSTD)

**Comment by szarnyasg** [comment]
The command-line flag `--format-options compression=gzip` solves most of the proposed problems except for ZSTD support.

**Comment by szarnyasg** [comment]
Documented in 836c2f833b2bc6321e4c4a2f0300644ea7dd5f4f.

**Comment by dszakallas** [comment]
There's ZSTD support in Hadoop 2.9.0 and newer:
https://issues.apache.org/jira/browse/HADOOP-13578
Technically Spark 3.1 support it however it's a bit tricky, see https://issues.apache.org/jira/browse/SPARK-34651
Spark 3.2.0 will ship support.
libhadoop is not build with zstd support by default so we might require a custom hadoop if we want to have it with Spark 3.1.0 / or in the raw serializer (as that is bare hadoop)

**Comment by szarnyasg** [comment]
I'm a big fan of zstd but found that currently most graph DBMSs only support loading from `csv.gz` or maybe `csv.bz2`. So I would not upgrade (or wait for) a new minor version of Spark just for this feature.

**Comment by dszakallas** [comment]
It could be still useful for compressing the intermediate data, for which my current best bet is to do with parquet / snappy.

**Comment by szarnyasg** [comment]
Intermediate (raw) data set compression has been added in #336
For the final data sets, `--format-options compression=gzip` works as documented in the README.
