### ISSUE TITLE
How to generate update streams with dates as Strings

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#29]
I set the `dateFormatter` to the `StringDateFormatter` in the `params.ini` file.

```
ldbc.snb.datagen.serializer.dateFormatter:ldbc.snb.datagen.serializer.formatter.StringDateFormatter
```

The node/property/relationships are fine, but the `updateStream_*` files contain epoch times. Is there a way to work around this?

**Comment by ArnauPrat** [comment]
It is not possible to change the format of update streams. Update streams are meant to be consumed only by the LDBC driver, which requires the time to be in epoch format for performance reasons.

**Comment by szarnyasg** [comment]
Thanks for the quicky reply - that makes sense!
