### ISSUE TITLE
Add person stream contains university that doesn't exist

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_snb_datagen_spark#3]
Hi,
I'm getting errors from trying to add a person to the database and then update their studyAt relationship to a university that doesn't exist. e.g.:

```
$ grep '805306368' *.csv
updateStream_0_0_person.csv:1388685681014|0|1|5497558139396|Eugene|Roindefo|female|383986676563|1388685681014|196.192.46.225|Chrome|1206|mg;en|Eugene5497558139396@gmx.com;Eugene5497558139396@hotmail.com|282;289;458;544;1164;1175;1191;1206;1532;1545;1765;1909;1953;1996;2030;2061;2777;2780;2781;2785;2786;2793;2797;2840;2984;3034;3054;3059;3060;4844;5183;6400;6945;6962;7012;7517;9097;9102;9333;11531;11695|805306368,2004|758,2010
updateStream_0_0_person.csv:1388980347766|0|1|5497558139187|Jimmy|Tsiranana|male|447319296852|1388980347766|41.188.18.41|Safari|1203|mg;en||6;1615;1616;1760;1953;2057;2082;2120;2783;2820;2845;3041;6377;6993;7380;7516;10222;11250|805306368,2005|758,2013
```

Please advise,
Tomer

**Comment by ArnauPrat** [comment]
Thanks @tomersagi 
I am looking into this right now.
Regards,
Arnau

**Comment by ArnauPrat** [comment]
I have pushed a fix for this and a script to validate the studyAt correctness.
Arnau

**Comment by tomersagi** [comment]
You owe me an hour and a half of head bashing against the keyboard :-)
Why on earth did you change the header of person_worksAt_organization_0_0.csv from Person.id|Organisation.id|workFrom| to Person.id|Organisation.id|**workFrom.id**| ?
In any case. please change it back in the next version. 
Thanks,

**Comment by tomersagi** [comment]
ok, add person works fine, now the update stream for addForum fails. Seems like U4 query adding a forum with a moderator is called before the U1 query adding that person has been called (http://pastebin.com/AWGiyvv4)[see error log here]

According to grep, the person was supposed to be created later:

        updateStream_0_0_forum.csv:1391037481721|1388657602144|4|42949675711|Group for Jesus in Beibei_District|1391037481721|5497558139028|6413
    updateStream_0_0_person.csv:1388657602144|0|1|5497558139028|Chen|Yang|female|588494961974|1388657602144|27.113.141.150|Firefox|420|zh;en|Chen5497558139028@fudge.com;Chen5497558139028@gmail.com;Chen5497558139028@hotmail.com;Chen549755813902 @marrakesh.cc;Chen5497558139028@yahoo.com|6;782;6413;9479|2207,2010|

**Comment by ArnauPrat** [comment]
Hi Tomer,
First of all sorry for all the inconveniences. Last week I spent some time fixing issues with file names, as they were not consistent with those in the previous version of datagen and the specification (especially those related to organisations). In the case of the workFrom issue, the column names were not in the correct order, and in the process of fixing them, I introduced this last "workFrom.id" error. I just pushed the fix.

About the other error, do you think this is a problem with the data or the driver?
According to the snippet you pasted, the person is created at 1388657602144 which is before the creation date of the forum (1391037481721). Please correct me but I think we should speak with @alexaverbuch about this issue as I think is driver related.

Regards,
Arnau

**Comment by alexaverbuch** [comment]
@tomersagi 
please add a printout to your `OperationHandler` implementations for `LdbcUpdate1AddPerson` (when `operation.timeStamp() == 1388657602144`) and `LdbcUpdate4AddForum` (when `operation.timeStamp() == 1391037481721`).
please add these printouts as the first and last lines of your handlers and then run the benchmark again.
I would like to see if the add forum handler is starting before the add person handler has completed

**Comment by alexaverbuch** [comment]
FYI, @ArnauPrat @tomersagi 
If the lines are printed in the *incorrect order* then it *definitely proves* that the bug is in the benchmark tools, probably the driver.
If the lines are printed in the *correct order* then it *does not prove or disprove* that the bug is in the benchmark tools (because this could be a race condition), but it makes it less likely.

My money is on this being one of two things:
  1. Driver
  2. Database (Titan is not transactional, so this could be an isolation limitation)

**Comment by tomersagi** [comment]
Hi Guys,
I already have a printout in my implementations. Closely examining the paste, I think option 2 is happening. Add person is invoked before add forum, but has either failed or not completed yet when add forum looks for the person just added. I think Titan is transactional and really can't see why this is happening. I'll have a closer look. 
Thanks for the assistance. 
I'll keep you posted.

**Comment by alexaverbuch** [comment]
@tomersagi,
Which backend are you using with Titan?
Titan, per se, is _definitely not_ transactional (e.g., if you use Cassandra as backend it will not be transactional), but the specific behavior is dependent on the backend you are using, as I'm sure you know. 
Is it Berkley DB at the moment?

**Comment by tomersagi** [comment]
Hi,
I'm using BerkeleyDB and looking at MapDB as an alternative. 
Tomer

**Comment by alexaverbuch** [comment]
In your previous comment you wrote

"Add person is invoked before add forum, but has either failed or not completed yet when add forum looks for the person just added"

Were at the printouts at the beginning AND end of the handler, allowing you to track when handlers both started and finished?

**Comment by tomersagi** [comment]
Only at the beginning, I'll add printouts at the end as well, but that may not say much since that will mark the end of the handler execution, I think the transaction is sent to a thread pool for execution so you don't know when it is actually invoked.

**Comment by alexaverbuch** [comment]
could you paste your handler code here please?
a handler should not return until the transaction has completed

**Comment by tomersagi** [comment]
Sorry, I've receieved SSRB and OSRB approval but still waiting on HPDC approval ;-) no code pastes yet, but I'll try and make sure it doesn't.

**Comment by alexaverbuch** [comment]
bureaucracy... :)

you don't need to send me any of the application logic, just the skeleton of the handler with the transactional API from Blueprints and a comment specifying where the application logic usually is

**Comment by tomersagi** [comment]
ok, I'll see what I can do. In the mean time, according to the new printouts, AddPerson completes before AddForum Commences so either the handler indeed finishes before the transaction is complete or it's a deeper problem with titan / BDB JE.

**Comment by alexaverbuch** [comment]
my job here is done :)

on a side note, LDBC SNB **requires** an ACID compliant database. it will likely not work (i.e., you will get these issues) with any non-transactional database

**Comment by tomersagi** [comment]
ok, solved. I was using 24 threads (server configuration) while debugging on my laptop. Reduced to 4 threads and added a forced commit at the end of update query 1 solved the issue.

**Comment by alexaverbuch** [comment]
please test with 24 threads and forced commit. reducing threads might just be decreasing the likelihood of a race condition.

**Comment by tomersagi** [comment]
No problems with with 24 threads and forced commit either.

**Comment by alexaverbuch** [comment]
great!

**Comment by tomersagi** [comment]
Thanks for your help @alexaverbuch and @ArnauPrat
