### ISSUE TITLE
Wrong JAR file generated for Spark 3.1 

### ISSUE THREAD

**Issue by marcelned** [ldbc/ldbc_snb_datagen_spark#300]
Upon invoking `tools/build.sh`

the following target is generated:

`./target/ldbc_snb_datagen_2.12_spark3.1-0.4.0-SNAPSHOT.jar`

even though I'm using spark-3.1.1-bin-hadoop2.7

This leads to an error at data generation process:

```console
./tools/run.py ./target/ldbc_snb_datagen_${PLATFORM_VERSION}-${DATAGEN_VERSION}.jar -- --help

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/Users/marcelcoetzee/Desktop/Work/DesktopStudy/spark/spark-3.1.1-bin-hadoop2.7/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/05/27 12:04:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/05/27 12:04:21 WARN DependencyUtils: Local jar /Users/marcelcoetzee/Desktop/Work/DesktopStudy/ldbc_snb_datagen/./target/ldbc_snb_datagen_2.12_spark3.1-0.4.0-SNAPSHOT.jar does not exist, skipping.
Error: Failed to load class ldbc.snb.datagen.spark.LdbcDatagen.
21/05/27 12:04:21 INFO ShutdownHookManager: Shutdown hook called
21/05/27 12:04:21 INFO ShutdownHookManager: Deleting directory /private/var/folders/1y/2vnd0_v16wn4bt34l8vncl9c0000gp/T/spark-cdd28640-327a-4432-ab2b-da9b59c8d5ed
```

**Comment by szarnyasg** [comment]
Hi @marcelned, thanks for reporting this.

I have trouble reproducing the issue locally (Fedora 34, Maven 3.6.1). Invoking the `tools/build.sh` should use the default Maven build profile and result in a JAR for `spark2.4`. Locally, it produced me `./target/ldbc_snb_datagen_2.11_spark2.4-0.4.0-SNAPSHOT.jar`.

Are you sure you the build generated the file `./target/ldbc_snb_datagen_2.12_spark3.1-0.4.0-SNAPSHOT.jar`?

I pushed a commit which adds parameter passthrough to the `tools/build.sh` script. So you can do:

```bash
tools/build.sh -Pspark3.1
```

This sets the Maven build profile to `spark3.1` and ensures that a Spark 3.1-compatible JAR file is generated.

**Comment by marcelned** [comment]
@szarnyasg The fix worked perfectly. Thank you!
