### ISSUE TITLE
Split CSV files for batches

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#314]
For large SFs, the insert CSVs are quite large - we should split them into smaller files.

**Comment by dszakallas** [comment]
(1) This is actually not so easy to do if we want to split based on the `sizeFactor` estimation

- We need to have size information in the BI writer, which we currently don't.  The BI graph doesn't change the relative sizes of the entities so we could actually reuse everything from the raw graph but the edge and attribute explosions do introduce new entities whose sizes should be estimated.

- Technically `Graph` and `GraphDef` should be the place to add the entity sizes. Adding it to `entities` requires lots of refactor. Instead I am more in favor of adding a new field `entityTraits: Map[EntityType, EntityTraitValue]`
```scala
case class EntityTraitValue(sizeFactor: Option[Double], schema: Option[StructType])
```
this could be inspected in the writer and could do something like
```scala
val numPartitions = Math.max(1, Math.ceil(sizeFactor / overSizeFactor).toInt)
df.repartitionByRange(numPartitions, $"creationDate")
```

This adds a considerable development effort.

(2) We could use `df.rdd.numPartitions` for each entity, as that will be the same as `sizeFactor / oversizeFactor`, at least where the previous transformations only included narrow operations. This is simple to do.
