### ISSUE TITLE
Drop support for Spark 2.4

### ISSUE THREAD

**Issue by dszakallas** [ldbc/ldbc_snb_datagen_spark#331]
Spark 3 has been released in Dec 2020. All major platforms are supporting it now. Maybe it's time to drop support for Spark 2.4?

**Comment by szarnyasg** [comment]
I'm in favour of dropping support for Spark 2.x.

Some of our users are already on the 3.x branch:
https://github.com/ldbc/ldbc_snb_datagen_spark/issues/324#issuecomment-918532634

**Comment by dszakallas** [comment]
The first step is moving to Spark 3.1 by default: #338

**Comment by dszakallas** [comment]
#336 removed Spark 2.4 support
