### ISSUE TITLE
Support LongDateFormatter

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#340]
The Hadoop variant had a `LongDateFormatter` which produced epoch numbers for the datatime values (e.g. `creationDate`):
https://github.com/ldbc/ldbc_snb_datagen_hadoop/blob/main/src/main/java/ldbc/snb/datagen/util/formatter/LongDateFormatter.java

This is a low priority issue, saving it here in case many users are interested (if so, let us know).

**Comment by szarnyasg** [comment]
Maybe the intermediate (raw) data set could use this to speed up reading it back.

**Comment by szarnyasg** [comment]
Loosely related PR: #336

**Comment by dszakallas** [comment]
Technically, this is actually rather easy to do. We just need to do an inverse transformation of https://github.com/ldbc/ldbc_snb_datagen_spark/blob/main/src/main/scala/ldbc/snb/datagen/transformation/transform/ConvertDates.scala.
