### ISSUE TITLE
Move to SBT

### ISSUE THREAD

**Issue by dszakallas** [ldbc/ldbc_snb_datagen_spark#343]
As we are moving an ever larger part of our codebase to Scala, we should discuss whether to move to SBT altogether and remove Maven support, so that we don't have to maintain two build systems.

SBT is the primary build system for Scala and is able to support our need of mixed Java/Scala compilation with the added benefit of having better support for Scala projects altogether, either from features shipping OOTB or through the wide range of plugins not available for Maven.
Some notable features:
- https://github.com/sbt/sbt-projectmatrix project matrix, enhancing dev experience of multi-platform builds with advanced features like platform depedent library project dependencies;, which in our case can come in handy as we are targeting Spark2.4/Spark3.1/... (although #331 would devalue this)
- https://scalameta.org/scalafmt/ the go-to code formatter doesn't have officially maintained Maven plugin
- Faster incremental builds
- Metals, a popular language server for Scala has better integration with SBT than with Maven https://scalameta.org/metals/docs/build-tools/overview

**Comment by szarnyasg** [comment]
I'm fine with moving away from Maven.

SBT can be slightly more difficult to set up locally but those who just want to generate a few small graphs can use our [Docker image](https://github.com/ldbc/ldbc_snb_datagen_spark/tree/main#docker-image).

**Comment by dszakallas** [comment]
Resolved by #409 .
