### ISSUE TITLE
SF 3K and SF 10K size observation

### ISSUE THREAD

**Issue by arvindshmicrosoft** [ldbc/ldbc_snb_datagen_spark#346]
I am seeing quite low storage sizes for the `bi/singular-merged-fk` data generation for these scale factors. This is from some older runs in August 2021, which were done with commit hash 36d6628e7717339f8d6720c7080cf008d6139d97. Albeit the NumPersons are the same as in the latest code.

| Scale factor | Total space (including inserts / deletes) | NumPersons | 
|--------------|--------------------------------------------|---------------|
| 3000 | 1.81 TiB (1,992,787,265,730 bytes) | 6,000,000  |
| 10000 | 7.35 TiB (8,083,192,057,724 bytes) |  20,900,000 |

In contrast, the sizes for 30K `bi/singular-merged-fk` (also generated with the same commit hash code) seem okay to me:

| Scale factor | Total space (including inserts / deletes) | NumPersons | 
|--------------|--------------------------------------------|---------------|
| 30000 | 30.1 TB (33,197,934,932,001 bytes) | 77,000,000 |

Any comments on the differences in the 3K and 10K sizes? We do expect those to be close to 3TiB and 10TiB respectively, correct?

**Comment by szarnyasg** [comment]
We found that a 3rd degree polynomial closely approximates the `numPerson` with `sf` as its input.

We have the `numPersons` dialled in for `sf`s 1...300.

```python
import numpy as np
import matplotlib.pyplot as plt

sf = [1, 3, 10, 30, 100, 300]
numPersons = [10620, 25870, 70800, 175950, 487700, 1230500]
sf_new = [1, 3, 10, 30, 100, 300, 1000]

logx = np.log(sf)
logy = np.log(numPersons)
coeffs = np.polyfit(logx,logy,deg=3)
poly = np.poly1d(coeffs)
yfit = lambda x: np.exp(poly(np.log(x)))
print(yfit(sf_new)[-1])

plt.loglog(sf_new,yfit(sf_new))
plt.show()
```

Will update `sf`s 1000, 3000, and 10000 shortly.

**Comment by szarnyasg** [comment]
I updated the sizes of SF3k and SF10k (3559d7094865bff03e2983d3b1a3c496e4b170d6 and 532257f52d9acb1c9ec3f593e7642d4d367ed33e).

Now, when run with the default settings (i.e. using the `composite-merged-fk` serialization format), the generator produces ~3000 GiB and ~10000 GiB of data sets for SF3000 and SF10000, respectively.
