### ISSUE TITLE
Determine paths with a given length

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#354]
A few of the BI queries require pairs of persons with a given distance.

The paramgen should produce this somehow. Example approach:

* Take 10 person nodes from China.
* Jump 4 hops using only Person-knows-Person edges while ensuring that persons don't repeat on a given path (e.g. 4 steps of a BFS).
* Take e.g. 100 pairs of persons (from the endpoint of the paths)

A potential optimization is to first filter down the Person-knows-Person edges to ones where both Persons are located in China. Of course, if we do this optimization, we may select person pairs between whom there is a shorter path among persons (some of) who are not in China.

We have two queries for this:

* [Q10](https://ldbcouncil.org/ldbc_snb_docs/bi-read-10.pdf) -> We need paths of 3 or 4 hops.

* [Q15](https://ldbcouncil.org/ldbc_snb_docs/bi-read-15.pdf) -> Variant (A) requires paths of exactly 2 hops, (B) requires paths of exactly 4 hops.

**Comment by szarnyasg** [comment]
+ add `sample`

**Comment by dszakallas** [comment]
I added sample and a sigmoid dampening at the start, so small graphs use larger samples:
| SF  | samples (abs) | samples (%) | 3 hops | 4 hops |
|-----|---------|-----------|--------------|----------|
| 0.1 | 209     | 88.20     | 139602       |  6858 |
| 0.3 | 410 | 72.39 |  630372 | 23125 |
| 1   | 548     | 36.72     | 2786062      | 114308 |
| 3   | 188     | 5.19      | 2870619      | 230007 |

I think SF 10 will already hit the floor of 100 samples, and sample size will be constant from then on.
