### ISSUE TITLE
Not a valid .JAR

### ISSUE THREAD

**Issue by maverick-zhn** [ldbc/ldbc_snb_datagen_spark#37]
Dear all,

I found a minor bug. Since, the pom.xml includes:
"<version>0.2.7</version>"

When running ./run.sh -> **Not a valid .JAR: /path/ldbc_dnb_datagen-0.2.5-jar-with-dependencies.jar** will appear. 

I will fix the .sh

Regards.

**Comment by ravibitsgoa** [comment]
Hi everyone,
I am getting this Not a valid .JAR: /path/ldbc_dnb_datagen-0.2.7-jar-with-dependencies.jar error.
Can anyone help me with this?

**Comment by szarnyasg** [comment]
Hi @ravibitsgoa . Did you set the value of the `LDBC_SNB_DATAGEN_HOME` variable? What command do you run that gives the error above?

**Comment by ravibitsgoa** [comment]
Yes, I did set LDBC_SNB_DATAGEN_HOME.
I got this error when running ./run.sh

**Comment by szarnyasg** [comment]
`run.sh` start with the message: **Running generator with the following parameters: ...**
Can you share your parameters? E.g. mine are:
```console ===============================================================================
Running generator with the following parameters:
-------------------------------------------------------------------------------
LDBC_SNB_DATAGEN_HOME: /home/szarnyasg/git/ldbc_snb_datagen
JAVA_HOME: /home/szarnyasg/.sdkman/candidates/java/current
HADOOP_HOME: /home/szarnyasg/hadoop-2.6.0
HADOOP_CLIENT_OPTS: -Xmx16G
===============================================================================
```

**Comment by ravibitsgoa** [comment]
Yes, sure. 
Mine are
LDBC_SNB_DATAGEN_HOME: /home/dreamlab/ldbc_snb_datagen
JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
HADOOP_HOME: /usr/local/hadoop
HADOOP_CLIENT_OPTS: -Xmx16G

**Comment by szarnyasg** [comment]
Your params seem good to me. And I suppose you have checked out the latest `master` branch, which should have this fix.
Is using Docker an option for you? There are instructions in the README detailing how to use it.

**Comment by ravibitsgoa** [comment]
Yes, I am using the latest master branch.
Sorry, I'm getting the same error, but with 0.2.7, not with 0.2.5.
Also, using Docker is not possible in my case.
I tried removing ldbc subdirectory of .m2 also, which did not work.

**Comment by szarnyasg** [comment]
The `/path` part is suspicious. Try running the `run.sh` script with `bash -x ./run.sh` and investigate what happens on this line:

```console
$HADOOP_HOME/bin/hadoop jar $LDBC_SNB_DATAGEN_HOME/target/ldbc_snb_datagen-0.2.7-jar-with-dependencies.jar $LDBC_SNB_DATAGEN_HOME/params.ini
```

For me, it gives:

```console
+ /home/szarnyasg/hadoop-2.6.0/bin/hadoop jar /home/szarnyasg/git/ldbc_snb_datagen/target/ldbc_snb_datagen-0.2.7-jar-with-dependencies.jar /home/szarnyasg/git/ldbc_snb_datagen/params.ini
```

**Comment by ravibitsgoa** [comment]
I am getting this:
`+ /usr/local/hadoop/bin/hadoop jar /home/dreamlab/ldbc_snb_datagen/target/ldbc_snb_datagen-0.2.7-jar-with-dependencies.jar /home/dreamlab/ldbc_snb_datagen/params.ini`

**Comment by ravibitsgoa** [comment]
Sorry for the inconvenience, the issue was with my local path only. Fixed.

**Comment by szarnyasg** [comment]
Great! Glad it worked out.
