### ISSUE TITLE
OOM when generate sf3000 in local

### ISSUE THREAD

**Issue by HarrisChu** [ldbc/ldbc_snb_datagen_spark#387]
when I generate sf3000, spark errors "java.lang.OutOfMemoryError: Java heap space"

```
tools/run.py ./target/ldbc_snb_datagen_${PLATFORM_VERSION}-${DATAGEN_VERSION}.jar \
        --parallelism 48 --memory 100G \
        -- \
        --format csv --scale-factor 3000 --mode interactive \
        --output-dir test_data
```

MemTotal:       251GB

could you provide the configuration when generate sf3000 in local?
Thanks.

**Comment by szarnyasg** [comment]
Hi, SF3000 needs quite a lot of memory. I recently generated the BI variant on AWS EMR where it ran on 24 r6gd.4xlarge machines, so it used 3TiB of RAM in total.

By the way, the Datagen's support for the Interactive workload is not complete, so even if you manage to get it running, this will not produce the correct data sets for Interactive. We are working on this with an ETA in the summer.

**Comment by HarrisChu** [comment]
> Hi, SF3000 needs quite a lot of memory. I recently generated the BI variant on AWS EMR where it ran on 24 r6gd.4xlarge machines, so it used 3TiB of RAM in total.
> 
> By the way, the Datagen's support for the Interactive workload is not complete, so even if you manage to get it running, this will not produce the correct data sets for Interactive. We are working on this with an ETA in the summer.

OK, thank you
