### ISSUE TITLE
Help with finding datagen version used for benchmarks

### ISSUE THREAD

**Issue by pawanrawal** [ldbc/ldbc_snb_datagen_spark#41]
This issue probably doesn't belong here but I would still appreciate if you could help me figure it out.

I am trying to replicate the benchmarks mentioned in this [paper](https://event.cwi.nl/grades/2017/12-Apaci.pdf). It uses the `ldbc_snb_datagen` to generate data for scale factors 3 and 10 and then loads them into various databases. 

In particular, I am facing problems while loading data into Postgres. I am using [this](https://github.com/anilpacaci/graph-benchmarking/blob/master/snb-interactive-sql/scripts/load_csv.sql) script to do so after loading the `db_schema.sql` and the `stored_procedures.sql`. I have noticed that the script expects certain columns (e.g. Creator to be part of Person table) and hence the script fails. You would notice that it doesn't try to read files like `comment_hasCreator_person_0_0.csv`, `post_hasCreator_person_0_0.csv` among others. 

My question is that do you know which version of the `ldbc_snb_datagen` is being used for these benchmarks? I have opened an issue [here](https://github.com/anilpacaci/graph-benchmarking/issues/18) but haven't got a reply yet. Any help would be much appreciated.

**Comment by szarnyasg** [comment]
Hello @pawanrawal, I am probably late to the party and I see that you've already received an answer at https://github.com/anilpacaci/graph-benchmarking/issues/18#issuecomment-326649888.
I'd just like to point out that we now maintain tables that contain the sizes of [SNB](https://github.com/ldbc/ldbc_snb_datagen/wiki/SNB-Interactive-and-BI) and [Graphalytics](https://github.com/ldbc/ldbc_snb_datagen/wiki/Graphalytics) data sets. These might prove useful when looking for a particular version of Datagen that was used to generate data sets in a given paper.
