### ISSUE TITLE
What do "fb" and "zf" suffix mean in datasets generated by datagen (available on graphalytics website)? 

### ISSUE THREAD

**Issue by lol** [ldbc/ldbc_snb_datagen_spark#412]
Hi,

I suppose "fb" refers to a Facebook-like social media graph.

But what does "zf" mean?

Context: Names of lot of datagen datasets have "fb" and "zf" as suffix. https://graphalytics.org/datasets I have also tried reading the relevant paper(s) but couldn't find the answer.

Thank you.

**Comment by szarnyasg** [comment]
Hi, 
It refers to a [Zipfian distribution](https://en.wikipedia.org/wiki/Zipf%27s_law) The Datagen implements this with the [`ZipfDistribution`](https://github.com/ldbc/ldbc_snb_datagen_hadoop/blob/main/src/main/java/ldbc/snb/datagen/generator/distribution/ZipfDistribution.java) class.

**Comment by lol** [comment]
Thank you!
