### ISSUE TITLE
How to generate a Zipfian Person knows Person?

### ISSUE THREAD

**Issue by ErvinXie** [ldbc/ldbc_snb_datagen_spark#426]
I try to launch with a --param-file zipf.ini, where the .ini file contents are

generator.degreeDistribution:Zipf
generator.distribution.ZipfDistribution.alpha:4

I checked the generated graph. It seems the option does not work.

**Comment by ErvinXie** [comment]
I found that **generator.degreeDistribution** is not passed to the generator while **generator.distribution.ZipfDistribution.alpha** is passed successfully. So I edited the source code to generate a Zipfian knows graph. But I suppose there should be some way to do this by config file?

**Comment by szarnyasg** [comment]
Hi, it's quite possible that this is a bug – the Spark Datagen was never tested with a Zipfian distribution. If you only need graphs up to SF1000 and do not mind a slower generation process, then it may make sense to use the old Hadoop-based Datagen where this feature (IIRC) worked: https://github.com/ldbc/ldbc_snb_datagen_hadoop/

If you have an LDBC CLA, you can also submit a PR – I'll be happy to review it.

**Comment by ErvinXie** [comment]
I found the file here set the degreeDistribution to _Facebook_ [https://github.com/ldbc/ldbc_snb_datagen_spark/blob/main/src/main/resources/scale_factors.xml](scale_factors.xml). GeneratorStage here https://github.com/ldbc/ldbc_snb_datagen_spark/blob/fbec425ecfbb89c3a563c60ad0066f0256631240/src/main/scala/ldbc/snb/datagen/generator/GenerationStage.scala#L81 load the config and overwrite the config in params file. Is this intended? to make sure that every scale factor to generate with Facebook distribution?

**Comment by szarnyasg** [comment]
Yes -- for the official benchmark data sets, we intend to use the Facebook distribution for every scale factor.

**Comment by ErvinXie** [comment]
Thank you so much for your help!
