### ISSUE TITLE
Datagen (Spark version) generate parameters error

### ISSUE THREAD

**Issue by nevermore3** [ldbc/ldbc_snb_datagen_spark#429]
When running the generate-all.sh script using datagen's docker  according to the requirements of the document, an error is reported during the parameter generation phase

```
============ Loading the factor tables ============
Loading personNumFriendsOfFriendsOfFriends
Loading personKnowsPersonDays
Loading personNumFriendTags
Loading personStudyAtUniversityDays
Loading tagClassNumMessages
Loading tagNumMessages
Loading people2Hops
Loading personNumFriends
Loading personNumFriendOfFriendForums
Loading personFirstNames
Loading messageIds
Loading creationDayAndTagClassNumMessages
Loading tagClassNumTags
Loading cityPairsNumFriends
Loading creationDayAndLengthCategoryNumMessages
Loading personKnowsPersonConnected
Loading countryNumMessages
Loading personDisjointEmployerPairs
Loading sameUniversityConnected
Loading creationDayNumMessages
Loading countryNumPersons
Loading creationDayAndTagNumMessages
Loading people4Hops
Loading personNumFriendOfFriendCompanies
Loading companyNumEmployees
Loading personDays
Loading personLikesNumMessages
Loading personNumFriendOfFriendPosts
Loading personWorkAtCompanyDays
Loading personNumFriendComments
Loading languageNumPosts
Loading cityNumPersons
Loading tagNumPersons
Loading lengthNumMessages
Loading countryPairsNumFriends
============ Factor Tables loaded ============
Traceback (most recent call last):
  File "paramgen.py", line 386, in <module>
    PG.run(args.generate_paths)
  File "paramgen.py", line 216, in run
    self.prepare_factor_tables(prepare_tables_params)
  File "paramgen.py", line 131, in prepare_factor_tables
    param_list = self.define_threshold_per_table(param_list)
  File "paramgen.py", line 104, in define_threshold_per_table
    raise ValueError(
ValueError:
                    Error when determining threshold: no parameters are returned for table personNumFriendsOfFriendsOfFriends
                    on column Person1Id. Start threshold: 2 Max threshold: 198
```

**Comment by szarnyasg** [comment]
I somehow completely missed this issue. Is this for very small scale factors? In any case, I'm transferring this issue to the Datagen.

**Comment by ggssh** [comment]
> When running the generate-all.sh script using datagen's docker according to the requirements of the document, an error is reported during the parameter generation phase
> 
> ```
> ============ Loading the factor tables ============
> Loading personNumFriendsOfFriendsOfFriends
> Loading personKnowsPersonDays
> Loading personNumFriendTags
> Loading personStudyAtUniversityDays
> Loading tagClassNumMessages
> Loading tagNumMessages
> Loading people2Hops
> Loading personNumFriends
> Loading personNumFriendOfFriendForums
> Loading personFirstNames
> Loading messageIds
> Loading creationDayAndTagClassNumMessages
> Loading tagClassNumTags
> Loading cityPairsNumFriends
> Loading creationDayAndLengthCategoryNumMessages
> Loading personKnowsPersonConnected
> Loading countryNumMessages
> Loading personDisjointEmployerPairs
> Loading sameUniversityConnected
> Loading creationDayNumMessages
> Loading countryNumPersons
> Loading creationDayAndTagNumMessages
> Loading people4Hops
> Loading personNumFriendOfFriendCompanies
> Loading companyNumEmployees
> Loading personDays
> Loading personLikesNumMessages
> Loading personNumFriendOfFriendPosts
> Loading personWorkAtCompanyDays
> Loading personNumFriendComments
> Loading languageNumPosts
> Loading cityNumPersons
> Loading tagNumPersons
> Loading lengthNumMessages
> Loading countryPairsNumFriends
> ============ Factor Tables loaded ============
> Traceback (most recent call last):
>   File "paramgen.py", line 386, in <module>
>     PG.run(args.generate_paths)
>   File "paramgen.py", line 216, in run
>     self.prepare_factor_tables(prepare_tables_params)
>   File "paramgen.py", line 131, in prepare_factor_tables
>     param_list = self.define_threshold_per_table(param_list)
>   File "paramgen.py", line 104, in define_threshold_per_table
>     raise ValueError(
> ValueError:
>                     Error when determining threshold: no parameters are returned for table personNumFriendsOfFriendsOfFriends
>                     on column Person1Id. Start threshold: 2 Max threshold: 198
> ```

I have the same problem.

**Comment by ggssh** [comment]
> I somehow completely missed this issue. Is this for very small scale factors? In any case, I'm transferring this issue to the Datagen.

Indeed, if the sf is set to a small size, the above error will occur.😭

**Comment by GLaDAP** [comment]
@ggssh Which scale factor did you try to generate?

**Comment by ggssh** [comment]
> @ggssh Which scale factor did you try to generate?

0.003

**Comment by GLaDAP** [comment]
Hi @ggssh @nevermore3, I have updated the generate all script to support scale factors smaller than 1 (0.003, 0.1 and 0.3). If you pull the latest commit from the main branch from the driver and implementations, the `generate-all.sh` should work. If not the case you can reopen the issue.
