### ISSUE TITLE
How to generate edge data with weight property?

### ISSUE THREAD

**Issue by mareden** [ldbc/ldbc_snb_datagen_spark#434]
LDBC SNB benchmark reference (https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf)  mentioned that 'Table D.8: Files output by the CsvBasic serializer using “raw data” mode (33 in total). The first part of the table contains the static entites, the second part contains the dynamic ones. Notation – C: entity category, N: node, E: edge.'
From this table D.8 I see file person_knows_person_*.csv contains a property 'weight'.

How is the data for weighted graph containing weighted edges like person_knows_person_*.csv is generated?

I tried to generate data with both ldbc_snb_datagen_hadoop and ldbc_snb_datagen_spark, but failed to combine the so-called "CsvBasic serializer using “raw data” mode", and failed to get weighted edges.

@szarnyasg Can I get your support on how to generate edges with weight property? Thanks.

**Comment by szarnyasg** [comment]
Hello, the table you referenced belong to the old Hadoop-based data generator which had support for edge weights. (The naming convention is `person_knows_person` in the old datagen and `Person_knows_Person` in the old one.)

My recommendation would be to come up with your own edge weights in post-processing. One approach is to add a random number. Another is to use one of the edge weights defined in the benchmark, e.g. [Q14's old variant](https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=70) or [new variant](https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=70).

**Comment by mareden** [comment]
> Hello, the table you referenced belong to the old Hadoop-based data generator which had support for edge weights. (The naming convention is `person_knows_person` in the old datagen and `Person_knows_Person` in the old one.)
> 
> My recommendation would be to come up with your own edge weights in post-processing. One approach is to add a random number. Another is to use one of the edge weights defined in the benchmark, e.g. [Q14's old variant](https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=70) or [new variant](https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=70).

Thank you for your suggestion, and quick response.
