### ISSUE TITLE
Inquiry: Is there any way to specify csv-singular-projected-fk serializer

### ISSUE THREAD

**Issue by kikimo** [ldbc/ldbc_snb_datagen_spark#435]
Hi, I read the LDBC SNB reference and found that there are four serializers available including:

1. csv-singular-projected-fk
2. csv-composite-projected-fk
3. csv-singular-merged-fk
4. csv-composite-merged-fk

I found that csv-composite-merged-fk is the default serializer and later when I want to switch to csv-singular-projected-fk serializer I can not find the coresponding conf item, so is there any way to do this?

**Comment by szarnyasg** [comment]
Hi, these can be adjusted by arguments passed to the datagen:
* the `--explode-attrs` argument implies the `singular` format
* the `--explode-edges` argument implies the `projected-fk` format
HTH. This should be documented, so let's this keep this issue open as a reminder to add this to the README.

**Comment by kikimo** [comment]
> Hi, these can be adjusted by arguments passed to the datagen:
> 
> * the `--explode-attrs` argument implies the `singular` format
> * the `--explode-edges` argument implies the `projected-fk` format
>   HTH. This should be documented, so let's this keep this issue open as a reminder to add this to the README.

Thanks a lot, it works.
