### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by LuisBosquez** [ldbc/ldbc_snb_datagen_spark#45]
I'm trying to download some of the existing data sets and I used the following command:
`
$ aws s3 sync s3://ldbc-snb.s3.amazonaws.com/ .
`
But got the following error:
```
fatal error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
```

Are the files still hosted there?

**Comment by ArnauPrat** [comment]
I have checked it, and the bucket exists. Probably you are getting an "access denied" error. This bucket is configured as "Requester pays" and thus annonymous access is not allowed. Do you have your credentials properly set?

**Comment by jdellithorpe** [comment]
I have the same problem. After configuring the aws cli per the instructions here:

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

I get the same output as @LuisBosquez . Is there anything special that needs to be done to access the dataset? Region settings or something?

Best,
Jonathan

**Comment by jdellithorpe** [comment]
After some fiddling around, I think I found the problem. The command should be:

`aws s3 ls ldbc-snb --request-payer`

The additional --request-payer option is required to send along the correct headers and generate the correct signature to indicate willingness to pay for access to the dataset (http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html).

**Comment by jdellithorpe** [comment]
Turns out the --request-payer option was really only added to `s3api` and the `s3 ls` command, but not to other subcommands like `sync` for some reason (see https://github.com/aws/aws-cli/issues/797).

I posted a patch in that thread as a temporary workaround.

**Comment by ArnauPrat** [comment]
Thanks @jdellithorpe for all your help. As I said by email, it turns out that I currently have my hadoop cluster out of service, and I don't know when it will be back again, and I need it to generate new datasets from the latest release that fixed several bugs. As soon as I have it back, I upload new and compressed data.

**Comment by szarnyasg** [comment]
Given that now there's a Docker image and most potential users have access to a machine that has enough resources to generate their graphs in a few hours, I propose that we should discontinue this until further notice.

**Comment by shrivijaya** [comment]
Unable to Ingest Accessory file due to An error occurred (NoSuchBucket) when calling the PutObjectTagging operation: The specified bucket does not exist

Please help on this

**Comment by szarnyasg** [comment]
@shrivijaya that's expected to be broken. Email me (address in next msg)

**Comment by szarnyasg** [comment]
szarnyasg@gmail.com

**Comment by Ashutosh3847719** [comment]
![Uploading echo_vakzz.jpg…]()

**Comment by Ashutosh3847719** [comment]
![_reverse_shell](![echo_vakzz](https://user-images.githubusercontent.com/26531785/120471249-1d71c880-c3c2-11eb-967a-0c1dc92afd20.jpg))

**Comment by Ashutosh3847719** [comment]
![echo_vakzz](https://user-images.githubusercontent.com/26531785/120471337-367a7980-c3c2-11eb-9d75-fb0a24f6c984.jpg)

**Comment by Ashutosh3847719** [comment]
![Uploading echo_vakzz.jpg…]()

**Comment by Ashutosh3847719** [comment]
![Uploading mk.jpg…]()

**Comment by Ashutosh3847719** [comment]
![Uploading download.png…]()

**Comment by Ashutosh3847719** [comment]
![Uploading mk.jpg…]()

**Comment by Ashutosh3847719** [comment]
![mk](https://user-images.githubusercontent.com/26531785/120472307-59595d80-c3c3-11eb-84a0-b8d169ed8db0.rb)

**Comment by Ashutosh3847719** [comment]
puts "hello from ruby"
`echo vakzz was here > /tmp/vakzz`
```

**Comment by Ashutosh3847719** [comment]
![Uploading echo_vakzz.jpg…]()
