### ISSUE TITLE
Implement generator for BI query 3

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#50]
https://github.com/ldbc/ldbc_snb_datagen/blob/master/paramgenerator/generateparamsbi.py#L117

**Comment by ArnauPrat** [comment]
Lol, I did not realize that this query did not have parameters XD

**Comment by szarnyasg** [comment]
Actually the generator was okay, but the serialization was missing: 615e48c9ac981c3ab77fcb267f4284409d2985ff
