### ISSUE TITLE
Is hadoop a dependency of this project?

### ISSUE THREAD

**Issue by tristan957** [ldbc/ldbc_snb_datagen_spark#67]
I ran the program with the example .ini file and received the following error: run.sh: line 21: /home/user/hadoop-2.6.0/bin/hadoop: No such file or directory

No data was generated

**Comment by szarnyasg** [comment]
Hi @tristan957, you have to provide your own installation of Hadoop 2.6. For detailed instructions, visit the [Configuration wiki page](https://github.com/ldbc/ldbc_snb_datagen/wiki/Configuration) of this repository.

**Comment by tristan957** [comment]
I actually just found that. I'm so dumb. Thank you

**Comment by tristan957** [comment]
I am experiencing a Java IOException error:
```java
Exception in thread "main" java.io.IOException: Mkdirs failed to create /var/folders/9_/tf8q165j5k5204_n9kmck10c0000gp/T/hadoop-unjar6265397963517346562/META-INF/license
	at org.apache.hadoop.util.RunJar.ensureDirectory(RunJar.java:128)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:104)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:81)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:209)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```
Run command: ```HADOOP_HOME=/Users/tristan.partin/Projects/ldbc_snb_datagen/hadoop-2.6.0/ LDBC_SNB_DATAGEN=/Users/tristan.partin/Desktop/ HADOOP_CLIENT_OPTS="-Xmx2G" JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home PARAM_GENERATION=false sh run.sh```

**Comment by szarnyasg** [comment]
I've never seen anything like this before. I wonder where `/var/folders` comes from?

**Comment by tristan957** [comment]
I believe that is the default temp folder in MacOS

**Comment by tristan957** [comment]
I could try it on a Linux machine if you think that would help

**Comment by tristan957** [comment]
Or I could change the permissions of the folder

**Comment by szarnyasg** [comment]
Both @ArnauPrat and I use Linux machines, so that's better tested. That said, Mac OS should be fine as well if you can write to `/var/folders`.

**Comment by tristan957** [comment]
permissions for folder are: drwxr-xr-x. Does that mean I don't have write access to folder?

**Comment by szarnyasg** [comment]
Do a chmod/chown, whatever it takes :-).

**Comment by tristan957** [comment]
Unable to change the permissions on the folder. Currently its 755, so I think I have read write access. I'm going to grab my Linux machine and see if it'll work from there. Keep you posted

**Comment by ArnauPrat** [comment]
I think that @alexaverbuch  has faced this same problem in the past. Is a Mac OSX only issue. 
I cannot help.

**Comment by tristan957** [comment]
Just for documentation purposes: https://github.com/sozykin/mipr/issues/2 https://stackoverflow.com/questions/10522835/hadoop-java-io-ioexception-mkdirs-failed-to-create-some-path this sucks

**Comment by tristan957** [comment]
Finally got it to run, but no output files were generated. Using `LDBC_SNB_DATAGEN=/Users/tristan.partin/Desktop/`

**Comment by szarnyasg** [comment]
Use the `LDBC_SNB_DATAGEN_HOME` var and set it to the root of this repository. For example, it's

```bash
export LDBC_SNB_DATAGEN_HOME=/home/user/git/ldbc_snb_datagen
```

**Comment by tristan957** [comment]
Had the wrong variable name. This has not been a good day. Thanks for dealing with my spam
