### ISSUE TITLE
turtle or n3 serialiser 

### ISSUE THREAD

**Issue by Gillani0** [ldbc/ldbc_snb_datagen_spark#7]
Hi, the previous version of SNB provides the n3 and turtle serialiser, however I can't find it in new code. Can you please help me in this matter. Cheers

**Comment by ArnauPrat** [comment]
Hi @Gillani0 
I worked on a Turtle serializer for the new version. To use it you'll need to set up the following variables inyour params.ini file after pulling the latest version:

```
ldbc.snb.datagen.serializer.personSerializer:ldbc.snb.datagen.serializer.snb.interactive.TurtlePersonSerializer
ldbc.snb.datagen.serializer.invariantSerializer:ldbc.snb.datagen.serializer.snb.interactive.TurtleInvariantSerializer
ldbc.snb.datagen.serializer.personActivitySerializer:ldbc.snb.datagen.serializer.snb.interactive.TurtlePersonActivitySerializer
```

I cannot guarantee it is free of bugs, but maybe you can try and test it.

Regards,

**Comment by Gillani0** [comment]
Thanks Arnau,
I was more in a need for a N-Quad file, so I managed to code it by myself according to my own use cases, but I will also try to test this one. Cheers
