### ISSUE TITLE
no data found

### ISSUE THREAD

**Issue by LarryLp** [ldbc/ldbc_snb_datagen_spark#70]
hi,I complied it with hadoop 2.7.3? I have already complied your project with hadoop2.7.3,and execute run.sh，it job seems to be worded,but I have got no data generated?where can I find it?

**Comment by szarnyasg** [comment]
Hi @LarryLp, we support Hadoop 2.6.0. Can you try using this version or you need to use 2.7.3 for some reason?

Cheers

**Comment by LarryLp** [comment]
@szarnyasg ok, thanks a lot! I will try it with Hadoop2.6.0, although I have only 2.7.3 presently.
