### ISSUE TITLE
person_likes_* dataset files sorted oppositely from rest of edge files

### ISSUE THREAD

**Issue by jdellithorpe** [ldbc/ldbc_snb_datagen_spark#74]
It appears that while all other dataset edge files are sorted by the SOURCE vertex for directed edges, the `person_likes_*` files are sorted by the DEST vertex. 

For example, `person_hasInterest_tag` lists edges in groups by the SOURCE person:

```
Person.id|Tag.id
933|59
933|291
933|565
933|569
933|779
...
1129|61
1129|62
1129|141
1129|205
...
```

However `person_likes_comment` files list edges in groups by the DEST comment:

```
Person.id|Comment.id|creationDate
32985348833579|2061584302097|2012-09-07T16:44:37.850+0000
4139|2061584302100|2012-07-21T08:37:04.052+0000
6597069777240|2061584302100|2012-07-24T21:46:12.715+0000
...
4139|1786706395175|2012-03-23T18:07:36.755+0000
6597069777240|1786706395175|2012-03-22T11:05:46.421+0000
...
```

While it's not technically a bug since edge ordering in the dataset files was never explicity specified, this difference in edge ordering between the files does create headaches for loader code, which in my case, takes advantage of the SOURCE vertex grouping of edges. The different ordering for `person_likes_*` edges means that code handling edge loading potentially needs to treat `person_likes_*` as a special case. In my particular case, I actually run a map-reduce job over the edge files anyway to generate the files sorted both ways (one set of files grouped by SOURCE vertex, and another group of files sorted by DEST vertex, for each directed edge type).

However the data generator decides to group edges by, either by SOURCE or DEST, ideally it should be consistent for all directed edge list files. 

As a side note... this different ordering for `person_likes_*` edge list files resulted in incorrect outgoing "like" edge lists from person vertices to messge vertices in my database, yet I still managed to pass validation (using the Neo4j validation dataset). Looking throug the benchmark, I realized the benchmark actually never validates traversals over like edges from person vertices TO message vertices, only message vertices TO person vertices (which were correct in my case). Thus, I hadn't actually discovered my bug until just now :)

**Comment by szarnyasg** [comment]
This is an interesting problem. Serialization of the likes is first triggered in https://github.com/ldbc/ldbc_snb_datagen/blob/dev/src/main/java/ldbc/snb/datagen/serializer/PersonActivityExporter.java, which traverses the Messages in Walls/Albums and looks up the Persons who liked them. This causes the serialized "likes" entries to be grouped by their Messages. Changing the traversal order would require quite a bit of refactoring with no clear added benefit.

Implementations are allowed to pre-process the data sets before loading (and many do so, typically with shell scripts). What's more, load times are not particularly important in SNB anyways (if they provide a reasonable speed, i.e. audited systems shouldn't require weeks to load the data).

So I'll close this as wontfix.
