### ISSUE TITLE
LDBC BI 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [ldbc/ldbc_snb_datagen_spark#79]
I read the documentation of the SNB data generator, but I didn't actually get the differnce between the workloads of interactive and BI. when to call the workload BI is it based on the scale factor ?

or in another way, how to generate a LDBC BI data set using the generator?

and where can I find the Queries of the interactive as BI workloads ?

Thank you for you help and support

**Comment by szarnyasg** [comment]
Hi @MohamedRagabAnas,

the BI and Interactive workloads use the same data sets, see the [SNB Interactive and BI](https://github.com/ldbc/ldbc_snb_datagen/wiki/SNB-Interactive-and-BI) wiki page for details.

The queries are defined in the [specification](https://github.com/ldbc/ldbc_snb_docs) using both a textual description and a graphical illustration. We also provide [reference implementations](https://github.com/ldbc/ldbc_snb_implementations). For these, we worked hard to ensure correctness, but we did not fine-tune their performance in every case, so their performance might not be representative.

Best,
Gabor

**Comment by MohamedRagabAnas** [comment]
Many Thank for your prompt reply!
I've generated the SNB dataset with small factor but I can't see the 'Message' and 'Forum' and other stuff needed forthe BI queries !
are these entities  related to the size generated (scale factor) or is there any parameters for generating them in the data ?
Thanks in advance for your reply !

**Comment by szarnyasg** [comment]
If you use one of the `params*.ini` files (except for `params-graphalytics.ini`), they should generate the whole graph. The Forums are in the `forum_*.csv` file, Messages are in the `comment_*.csv` and `post_*.csv` files, etc.
See section 2.3.4 of the [spec](https://ldbc.github.io/ldbc_snb_docs_snapshot/ldbc-snb-specification.pdf) for details.

**Comment by MohamedRagabAnas** [comment]
Yes, I have That's right, I've overlooked them !
Thank You very much :)
