### ISSUE TITLE
update stream: person adds post before becoming member of forum

### ISSUE THREAD

**Issue by alexaverbuch** [ldbc/ldbc_snb_datagen_spark#9]
I created a validation dataset using 

```
ldbc.snb.datagen.generator.numPersons:3000
ldbc.snb.datagen.generator.numYears:1
ldbc.snb.datagen.generator.startYear:2010
ldbc.snb.datagen.serializer.compressed:false
ldbc.snb.datagen.serializer.personSerializer:ldbc.snb.datagen.serializer.snb.interactive.CSVMergeForeignPersonSerializer
ldbc.snb.datagen.serializer.invariantSerializer:ldbc.snb.datagen.serializer.snb.interactive.CSVMergeForeignInvariantSerializer
ldbc.snb.datagen.serializer.personActivitySerializer:ldbc.snb.datagen.serializer.snb.interactive.CSVMergeForeignPersonActivitySerializer
ldbc.snb.datagen.serializer.updateStreams:true
ldbc.snb.datagen.serializer.numUpdatePartitions:6
ldbc.snb.datagen.serializer.outputDir:/Users/alexaverbuch/hadoopTempDir/output/
ldbc.snb.datagen.generator.numThreads:8
ldbc.snb.datagen.generator.numPartitions:1
```

and have found that in `updateStream_0_4_forum.csv` this line (Line 9861 --- Add Post)
`1294783648083|1293778021203|6|42949894023||1294783648083|200.93.242.168|Safari|tk|About Isabella I of Castil. About Samuel Johnson, his . About Johnny Carson, their. About Spain, The sec.|105|5497558140960|25769815355|47|1771;2038;3076;6424`

occurs before this line (Line 9950 --- Add Forum Membership)
`1294791536201|1293778021203|5|25769815355|5497558140960|1294791536201`

i.e., _Person_ `5497558140960` **adds** _Post_ `42949894023`  to _Forum_ `25769815355` before **becoming member** of that _Forum_

is this valid behavior?

**Comment by ArVr** [comment]
Offtopic:

Through your posted I finally manged to export data as CSV Merge Foreign. I couldn't find it anywhere in the Wiki or in the LDBC SNB Documentation. In the documentation they only describe the options but not how you can execute them (or did i overlooked it?).

**Comment by alexaverbuch** [comment]
@ArnauPrat can we close this?
