### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by PerFuchs** [ldbc/ldbc_snb_datagen_spark#90]
When I run the command `docker build . --tag ldbc/datagen`, as instructed in the README file, I get the following error. Is there anything you can do about this problem?

Sending build context to Docker daemon   1.68GB
Step 1/10 : FROM openjdk:8-jdk-alpine
 ---> a3562aa0b991
Step 2/10 : WORKDIR /opt
 ---> Using cache
 ---> 3dccf105f593
Step 3/10 : RUN apk add bash curl maven python
 ---> Running in 61489f0ed6a5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  bash (missing):
    required by: world[bash]
  curl (missing):
    required by: world[curl]
  maven (missing):
    required by: world[maven]
  python (missing):
    required by: world[python]
The command '/bin/sh -c apk add bash curl maven python' returned a non-zero code: 4

**Comment by szarnyasg** [comment]
I deleted my Docker cache and this seems to be working now. Let us know if it works for you.

**Comment by szarnyasg** [comment]
FYI, I merged #84 in the meantime which introduces Debian Stretch instead of Alpine Linux for the Docker image.

**Comment by PerFuchs** [comment]
That solved the issue. Thanks a lot!
