### ISSUE TITLE
Microbatching

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#91]
* [x] Separate static and dynamic data
* [x] Refactor Serialisers and 'objects' (entities) to remove redundant code
* [ ] Add Timestamps to all edges which currently lack them based on source node
* [ ] Add hadoop job to sort each file based on time buckets

Bucket size not configurable here as files will be read in via drive still which will handle microbatching. This allows full batch, micro batch and streaming to be decoupled from the datagen.

**Comment by jackwaudby** [comment]
Closing this issue and moving the discussion to #176
