### ISSUE TITLE
Introduce deletions

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#92]
Start with Messages - the difficulty is leaf Comments < Comments < Posts.

**Comment by szarnyasg** [comment]
Deletions are now accessible in the separate 'Interactive' document: https://ldbc.github.io/ldbc_snb_docs_snapshot/interactive-workload.pdf

**Comment by jackwaudby** [comment]
1. Defined 8 delete operations. 
2. Defined lifespan constraints for each dynamic entity. 
3.

**Comment by jackwaudby** [comment]
### Progress update

1. [x] Defined [8 delete operations](https://ldbc.github.io/ldbc_snb_docs_snapshot/interactive-workload.pdf)
2. [x] Each dynamic entity has a _lifespan_, comprised of attributes _creation date_ and _deletion date_. For each dynamic entity we defined the interval in which lifespan attributes can be selected. Each attribute is then sampled uniformly from its interval.

**We now have a _correct_ but _unrealistic_ dynamic graph**

Problems:
1. how do we extract delete operations using the generated lifespan attributes? 
2. how do we control the number of delete operations? 
3. sampling deletion dates uniformly from the interval is a naive approach, how do we make this selection more realistic?

Informally, the problems can be summarised as _if_ something is deleted (2.), _when_ it is deleted (3.) and _how_ do we turn it into a deletion operation (1.). 

To answer 2. we assign each dynamic entity a probability of being _explicitly_ deleted within the simulation period, where explictly means this event becomes a delete operation in the workload. This probability may be a function of several entity attributes. For example, people with more friends have a lower probability of being explicitly deleted. 

To answer 3. if an entity has been selected for explicit deletion we can select more realistic distributions to sample the deletion date from. For example, a comment may be more likely to be deleted nearer to the post creation date.

To answer 1. we give each dynamic entity a _deletion flag_, which is set if that entity is selected for explicit deletion in 2. This is then used in the serialization step when produces the `updateStreams` and `updateBatches` see issue #176 for more details.

**Comment by szarnyasg** [comment]
Flag deletes as **explicit** (everything else is **implicit** caused by a **cascading deletion**).

Requires multiple rounds of simulation, e.g. start by deleting Persons, check the number of _implicit deletes_ caused, determine how many Forums, Posts/Comments need to be deleted, etc.

**Comment by szarnyasg** [comment]
Continued in #176
